import Mathlib

/-!
# Sl2/Basic

Part of the blueprint for algebraic quantum representation theory.
See `blueprint/src/content.tex`, §"$\sltwo$-triples and primitive vectors"
(`sec:sl2-basic`). The primitive-vector string calculus itself is already in
Mathlib (`Mathlib.Algebra.Lie.Sl2`); the only new content here is the
explicit standard module `V(n)` (`def:sl2-standard-module`).
-/

noncomputable section

namespace QuantumRepresentationTheory

open Module (Basis)

/-- **Standard module `V(n)`, underlying carrier** (`def:sl2-standard-module`).
An `(n+1)`-dimensional `K`-vector space with standard basis `v_0, …, v_n`. -/
@[reducible] def StandardSl2Module (K : Type*) (n : ℕ) : Type _ := Fin (n + 1) → K

variable {K : Type*} [Field K] {n : ℕ}

instance : AddCommGroup (StandardSl2Module K n) :=
  inferInstanceAs (AddCommGroup (Fin (n + 1) → K))

instance : Module K (StandardSl2Module K n) :=
  inferInstanceAs (Module K (Fin (n + 1) → K))

/-- The standard basis vector `v_k` of `StandardSl2Module K n`. -/
def StandardSl2Module.v (k : Fin (n + 1)) : StandardSl2Module K n :=
  Pi.single k 1

variable {L : Type*} [LieRing L] [LieAlgebra K L] {h e f : L}

section Construction

/-!
### Construction of `standardSl2ModuleLieRingModule`

The hypothesis `CharZero K` is necessary and was missing from an earlier
version of these declarations: it is what makes `{e,f,h}` linearly
independent (needed below to extract well-defined coefficients of a
subalgebra element), via the fact that they are eigenvectors of `ad h` for
the pairwise-distinct eigenvalues `2, -2, 0`. Without it (e.g. in
characteristic `2`, where `[h,e] = 2e = 0` forces no constraint at all
relating `h` to `e`), an `sl₂`-triple need not even have `{e,f,h}` linearly
independent.

The construction: build the three generator actions `ρE, ρF, ρH` directly as
endomorphisms of `StandardSl2Module K n` from the formulas in the docstring
below, show they satisfy the `sl₂` bracket relations (`[ρE,ρF] = ρH`,
`[ρH,ρE] = 2ρE`, `[ρH,ρF] = -2ρF`), then transport this along a basis
`{e,f,h}` of the subalgebra (via `Basis.mk`/`Basis.constr`) to a genuine Lie
algebra homomorphism `Φ` from the subalgebra into `Module.End K
(StandardSl2Module K n)`, whose bracket-compatibility on the generators
extends to all of the subalgebra by bilinearity of both sides of
`Φ ⁅x,y⁆ = ⁅Φ x, Φ y⁆`.
-/

variable [CharZero K] {t : IsSl2Triple h e f}

private theorem linearIndependent_efh (t : IsSl2Triple h e f) :
    LinearIndependent K ![e, f, h] := by
  set adh : Module.End K L := LieModule.toEnd K L L h with hadh_def
  have hae : adh.HasEigenvector (2 : K) e := by
    refine ⟨?_, t.e_ne_zero⟩
    rw [Module.End.mem_eigenspace_iff, hadh_def, LieModule.toEnd_apply_apply]
    exact t.lie_h_e_smul K
  have haf : adh.HasEigenvector (-2 : K) f := by
    refine ⟨?_, t.f_ne_zero⟩
    rw [Module.End.mem_eigenspace_iff, hadh_def, LieModule.toEnd_apply_apply,
      t.lie_lie_smul_f K]
    module
  have hah : adh.HasEigenvector (0 : K) h := by
    refine ⟨?_, t.h_ne_zero⟩
    rw [Module.End.mem_eigenspace_iff, hadh_def, LieModule.toEnd_apply_apply, lie_self,
      zero_smul]
  have hinj : Function.Injective (![(2 : K), -2, 0]) := by
    intro i j hij
    fin_cases i <;> fin_cases j <;> simp at hij <;>
      first
      | rfl
      | (exfalso; norm_num at hij)
  refine adh.eigenvectors_linearIndependent' ![(2 : K), -2, 0] hinj ![e, f, h] ?_
  intro i
  fin_cases i
  · simpa using hae
  · simpa using haf
  · simpa using hah

omit [CharZero K] in
private theorem span_efh_eq (t : IsSl2Triple h e f) :
    Submodule.span K (Set.range ![e, f, h]) = (t.toLieSubalgebra (R := K)).toSubmodule := by
  rw [IsSl2Triple.toLieSubalgebra]
  congr 1
  ext x
  simp only [Set.mem_range, Set.mem_insert_iff, Set.mem_singleton_iff]
  constructor
  · rintro ⟨i, rfl⟩; fin_cases i <;> simp
  · rintro (rfl | rfl | rfl)
    · exact ⟨0, rfl⟩
    · exact ⟨1, rfl⟩
    · exact ⟨2, rfl⟩

/-- The generators `(e,f,h)`, as elements of the subalgebra subtype. -/
private def efhSub (t : IsSl2Triple h e f) : Fin 3 → ↥(t.toLieSubalgebra (R := K)) := fun i =>
  ⟨![e, f, h] i, by
    rw [← LieSubalgebra.mem_toSubmodule, ← span_efh_eq t]
    exact Submodule.subset_span (Set.mem_range_self i)⟩

/-- A basis of the `sl₂`-subalgebra generated by `t`, given by `(e,f,h)`. -/
private def subalgebraBasis (t : IsSl2Triple h e f) :
    Basis (Fin 3) K ↥(t.toLieSubalgebra (R := K)) :=
  Basis.mk (v := efhSub t)
    (LinearIndependent.of_comp (t.toLieSubalgebra (R := K)).toSubmodule.subtype
      (show LinearIndependent K
          (⇑(t.toLieSubalgebra (R := K)).toSubmodule.subtype ∘ efhSub t) from
        linearIndependent_efh t))
    (by
      intro x _
      have hx : (x : L) ∈ Submodule.span K (Set.range ![e, f, h]) := by
        rw [span_efh_eq t, LieSubalgebra.mem_toSubmodule]
        exact x.2
      obtain ⟨c, hc⟩ := (Submodule.mem_span_range_iff_exists_fun K).mp hx
      rw [Submodule.mem_span_range_iff_exists_fun]
      refine ⟨c, ?_⟩
      ext
      push_cast
      simpa [efhSub] using hc)

private theorem subalgebraBasis_apply (t : IsSl2Triple h e f) (i : Fin 3) :
    (subalgebraBasis (K := K) t i : L) = ![e, f, h] i := by
  simp [subalgebraBasis, Basis.mk_apply, efhSub]

/-- `e` acting on `StandardSl2Module K n`: `ρE (v k) = (k(n-k+1)) • v (k-1)`, `ρE (v 0) = 0`.
As a per-component formula (component `k` of the output reads from input component `k+1`,
scaled by the coefficient attached to *that* input index): zero at `k = n` (nothing shifts
down into the top component), else `((k+1)(n-k)) • w (k+1)`. -/
private def ρE : Module.End K (StandardSl2Module K n) where
  toFun w k := if hk : (k : ℕ) = n then 0
    else (((k : ℕ) + 1) * (n - (k : ℕ)) : K) * w ⟨(k : ℕ) + 1, by omega⟩
  map_add' x y := by funext k; simp; split_ifs <;> ring
  map_smul' c x := by funext k; simp; split_ifs <;> ring

/-- `f` acting on `StandardSl2Module K n`: `ρF (v k) = v (k+1)`, `ρF (v n) = 0`. -/
private def ρF : Module.End K (StandardSl2Module K n) where
  toFun w k := if hk : (k : ℕ) = 0 then 0 else w ⟨(k : ℕ) - 1, by omega⟩
  map_add' x y := by funext k; simp only [Pi.add_apply]; split_ifs <;> ring
  map_smul' c x := by
    funext k; simp only [Pi.smul_apply, smul_eq_mul, RingHom.id_apply]; split_ifs <;> ring

/-- `h` acting on `StandardSl2Module K n`: `ρH (v k) = (n - 2k) • v k`. -/
private def ρH : Module.End K (StandardSl2Module K n) where
  toFun w k := ((n : K) - 2 * (k : ℕ)) * w k
  map_add' x y := by funext k; simp only [Pi.add_apply]; ring
  map_smul' c x := by funext k; simp only [Pi.smul_apply, smul_eq_mul, RingHom.id_apply]; ring

omit [CharZero K] in
private theorem ρH_v (k : Fin (n + 1)) :
    (ρH : Module.End K (StandardSl2Module K n)) (StandardSl2Module.v k)
      = ((n : K) - 2 * (k : ℕ)) • StandardSl2Module.v k := by
  funext j
  simp only [ρH, LinearMap.coe_mk, AddHom.coe_mk, StandardSl2Module.v, Pi.single_apply,
    Pi.smul_apply, smul_eq_mul]
  split_ifs with hjk <;> simp_all

omit [CharZero K] in
private theorem ρF_v_lt (k : Fin (n + 1)) (hk : (k : ℕ) < n) :
    (ρF : Module.End K (StandardSl2Module K n)) (StandardSl2Module.v k)
      = StandardSl2Module.v ⟨(k : ℕ) + 1, by omega⟩ := by
  funext j
  simp only [ρF, LinearMap.coe_mk, AddHom.coe_mk, StandardSl2Module.v, Pi.single_apply,
    Fin.ext_iff]
  split_ifs with hj hjk hjk <;> first | rfl | omega

omit [CharZero K] in
private theorem ρF_v_last :
    (ρF : Module.End K (StandardSl2Module K n)) (StandardSl2Module.v (Fin.last n)) = 0 := by
  funext j
  simp only [ρF, LinearMap.coe_mk, AddHom.coe_mk, Pi.zero_apply]
  split_ifs with hj
  · rfl
  · simp only [StandardSl2Module.v, Pi.single_apply, Fin.ext_iff, Fin.val_last]
    rw [if_neg]
    omega

private theorem ρE_v_pos (k : Fin (n + 1)) (hk : 0 < (k : ℕ)) :
    (ρE : Module.End K (StandardSl2Module K n)) (StandardSl2Module.v k)
      = ((k : ℕ) * (n - (k : ℕ) + 1) : K) • StandardSl2Module.v ⟨(k : ℕ) - 1, by omega⟩ := by
  have hkn : (k : ℕ) ≤ n := Nat.lt_succ_iff.mp k.isLt
  funext j
  simp only [ρE, LinearMap.coe_mk, AddHom.coe_mk, StandardSl2Module.v, Pi.single_apply,
    Pi.smul_apply, smul_eq_mul, Fin.ext_iff]
  split_ifs with hj hjk hjk <;>
    first
    | rfl
    | (exfalso; omega)
    | (have hjk' : ((k : ℕ) : K) = ((j : ℕ) : K) + 1 := by exact_mod_cast hjk.symm
       rw [hjk']; ring)
    | ring

omit [CharZero K] in
private theorem ρE_v_zero :
    (ρE : Module.End K (StandardSl2Module K n)) (StandardSl2Module.v ⟨0, Nat.succ_pos n⟩) = 0 := by
  funext j
  simp only [ρE, LinearMap.coe_mk, AddHom.coe_mk, Pi.zero_apply, StandardSl2Module.v,
    Pi.single_apply, Fin.ext_iff]
  split_ifs with hj hjk <;> first | rfl | (exfalso; omega) | ring

/-- **The `sl₂` relations hold for `(ρH,ρE,ρF)` on `StandardSl2Module K n`**: `[ρE,ρF]=ρH`,
`[ρH,ρE]=2ρE`, `[ρH,ρF]=-2ρF`. Checked componentwise on an arbitrary vector `w`: each
composite operator, evaluated at output index `j`, only ever reads `w j` itself (the
`E`/`F` shifts cancel), so the identity reduces to the coefficient computation already
recorded in the `ρ_v` lemmas' docstrings. -/
private theorem rel_ef :
    ⁅(ρE : Module.End K (StandardSl2Module K n)), (ρF : Module.End K (StandardSl2Module K n))⁆
      = ρH := by
  rw [LieRing.of_associative_ring_bracket]
  apply LinearMap.ext; intro w
  funext j
  simp only [LinearMap.sub_apply, Module.End.mul_apply, ρE, ρF, ρH, LinearMap.coe_mk,
    AddHom.coe_mk, Pi.sub_apply]
  have h1 : ¬ ((j : ℕ) + 1 = 0) := Nat.succ_ne_zero _
  simp only [dif_neg h1, Nat.add_sub_cancel]
  by_cases hjn : (j : ℕ) = n
  · rw [dif_pos hjn]
    have h0 : ¬ (j : ℕ) = 0 → ¬ ((j : ℕ) - 1 = n) := by omega
    by_cases hj0 : (j : ℕ) = 0
    · rw [dif_pos hj0]
      have hj0K : (j : K) = 0 := by exact_mod_cast hj0
      have hn0K : (n : K) = 0 := by exact_mod_cast (show n = 0 by omega)
      rw [hj0K, hn0K]; ring
    · -- `hj0 : ¬(j:ℕ) = 0` is a genuine local hypothesis here (from `by_cases`), so the
      -- inline `by omega` bound proofs below can see it (unlike when these facts were
      -- stated as reusable `(j:ℕ) ≠ 0 → …` implications before the case split, where the
      -- anonymous arrow binder wasn't visible to `omega` in the embedded proof term).
      have hsub : (((j : ℕ) - 1 : ℕ) : K) = (j : K) - 1 := by
        rw [Nat.cast_sub (by omega : 1 ≤ (j : ℕ))]; norm_num
      have hidx : (⟨(j : ℕ) - 1 + 1, by omega⟩ : Fin (n + 1)) = j := by
        apply Fin.ext; show (j : ℕ) - 1 + 1 = (j : ℕ); omega
      rw [dif_neg hj0, dif_neg (h0 hj0), hidx, hsub]
      have hjnK : (j : K) = (n : K) := by exact_mod_cast hjn
      rw [hjnK]; ring
  · rw [dif_neg hjn]
    by_cases hj0 : (j : ℕ) = 0
    · rw [dif_pos hj0]
      have hj0K : (j : K) = 0 := by exact_mod_cast hj0
      have hidx0 : w j = w (⟨0, Nat.succ_pos n⟩ : Fin (n + 1)) := by congr 1; exact Fin.ext hj0
      rw [hj0K, hidx0]; ring
    · have hjn1 : ¬ ((j : ℕ) - 1 = n) := by omega
      have hsub : (((j : ℕ) - 1 : ℕ) : K) = (j : K) - 1 := by
        rw [Nat.cast_sub (by omega : 1 ≤ (j : ℕ))]; norm_num
      have hidx : (⟨(j : ℕ) - 1 + 1, by omega⟩ : Fin (n + 1)) = j := by
        apply Fin.ext; show (j : ℕ) - 1 + 1 = (j : ℕ); omega
      rw [dif_neg hj0, dif_neg hjn1, hidx, hsub]
      ring

omit [CharZero K] in
private theorem rel_he :
    ⁅(ρH : Module.End K (StandardSl2Module K n)), (ρE : Module.End K (StandardSl2Module K n))⁆
      = (2 : K) • ρE := by
  rw [LieRing.of_associative_ring_bracket]
  apply LinearMap.ext; intro w
  funext j
  simp only [LinearMap.sub_apply, Module.End.mul_apply, LinearMap.smul_apply, Pi.smul_apply,
    smul_eq_mul, ρE, ρH, LinearMap.coe_mk, AddHom.coe_mk, Pi.sub_apply]
  by_cases hjn : (j : ℕ) = n
  · rw [dif_pos hjn, dif_pos hjn]; ring
  · rw [dif_neg hjn, dif_neg hjn]
    have hj1 : (((j : ℕ) + 1 : ℕ) : K) = (j : K) + 1 := by push_cast; ring
    rw [hj1]
    ring

omit [CharZero K] in
private theorem rel_hf :
    ⁅(ρH : Module.End K (StandardSl2Module K n)), (ρF : Module.End K (StandardSl2Module K n))⁆
      = (-2 : K) • ρF := by
  rw [LieRing.of_associative_ring_bracket]
  apply LinearMap.ext; intro w
  funext j
  simp only [LinearMap.sub_apply, Module.End.mul_apply, LinearMap.smul_apply, Pi.smul_apply,
    smul_eq_mul, ρF, ρH, LinearMap.coe_mk, AddHom.coe_mk, Pi.sub_apply]
  by_cases hj0 : (j : ℕ) = 0
  · rw [dif_pos hj0, dif_pos hj0]; ring
  · rw [dif_neg hj0, dif_neg hj0]
    have hsub : (((j : ℕ) - 1 : ℕ) : K) = (j : K) - 1 := by
      rw [Nat.cast_sub (by omega : 1 ≤ (j : ℕ))]; norm_num
    rw [hsub]
    ring

omit [CharZero K] in
/-- Antisymmetry of the bracket on `Module.End K (StandardSl2Module K n)`, proved directly via
the associative-ring commutator rather than via the generic `lie_skew` (which fails to
syntactically match brackets here, apparently due to an instance diamond between the different
routes Mathlib derives a `LieRing`/`Bracket` structure on an endomorphism ring). -/
private theorem endLieSkew (a b : Module.End K (StandardSl2Module K n)) : ⁅a, b⁆ = -⁅b, a⁆ := by
  rw [LieRing.of_associative_ring_bracket, LieRing.of_associative_ring_bracket]
  noncomm_ring

omit [CharZero K] in
/-- Bilinearity of the bracket on `Module.End K (StandardSl2Module K n)`, proved directly via
the associative-ring commutator for the same reason as `endLieSkew`. -/
private theorem endAddLie (a b c : Module.End K (StandardSl2Module K n)) :
    ⁅a + b, c⁆ = ⁅a, c⁆ + ⁅b, c⁆ := by
  simp only [LieRing.of_associative_ring_bracket, add_mul, mul_add]; abel

omit [CharZero K] in
private theorem endLieAdd (a b c : Module.End K (StandardSl2Module K n)) :
    ⁅a, b + c⁆ = ⁅a, b⁆ + ⁅a, c⁆ := by
  simp only [LieRing.of_associative_ring_bracket, add_mul, mul_add]; abel

omit [CharZero K] in
private theorem endSmulLie (r : K) (a b : Module.End K (StandardSl2Module K n)) :
    ⁅r • a, b⁆ = r • ⁅a, b⁆ := by
  simp only [LieRing.of_associative_ring_bracket, smul_sub, smul_mul_assoc, mul_smul_comm]

omit [CharZero K] in
private theorem endLieSmul (r : K) (a b : Module.End K (StandardSl2Module K n)) :
    ⁅a, r • b⁆ = r • ⁅a, b⁆ := by
  simp only [LieRing.of_associative_ring_bracket, smul_sub, smul_mul_assoc, mul_smul_comm]

/-- The Lie-algebra homomorphism from the `sl₂`-subalgebra generated by `t` into
`Module.End K (StandardSl2Module K n)`, sending `e ↦ ρE`, `f ↦ ρF`, `h ↦ ρH`. Built by
transporting `![ρE,ρF,ρH]` along the basis `subalgebraBasis t`; the fact that it respects
brackets (`Φ_lie`, below) is checked on the generators via `rel_ef`/`rel_he`/`rel_hf` and
then extended to the whole subalgebra by bilinearity. -/
private def Φ (t : IsSl2Triple h e f) :
    ↥(t.toLieSubalgebra (R := K)) →ₗ[K] Module.End K (StandardSl2Module K n) :=
  (subalgebraBasis t).constr K ![ρE, ρF, ρH]

private theorem Φ_apply (t : IsSl2Triple h e f) (i : Fin 3) :
    Φ t (subalgebraBasis t i) = ![(ρE : Module.End K (StandardSl2Module K n)), ρF, ρH] i :=
  Basis.constr_basis _ _ _ _

/-- Transports a bracket identity among the generators `(e,f,h)` down to the corresponding
identity among the basis elements `subalgebraBasis t 0,1,2` of the subalgebra. -/
private theorem lie_subalgebraBasis (t : IsSl2Triple h e f) (i j k : Fin 3) (c : K)
    (hc : ⁅![e, f, h] i, ![e, f, h] j⁆ = c • ![e, f, h] k) :
    ⁅subalgebraBasis (K := K) t i, subalgebraBasis (K := K) t j⁆
      = c • subalgebraBasis (K := K) t k := by
  apply Subtype.ext
  simp only [LieSubalgebra.coe_bracket, subalgebraBasis_apply, SetLike.val_smul]
  exact hc

/-- **`Φ` respects brackets, on the three generators** (the base case for `Φ_lie` below).
Checked pairwise on `(e,f,h)`: the diagonal is trivial (`lie_self`), and the six off-diagonal
cases follow from `t`'s defining relations (`lie_e_f`, `lie_h_e_smul`, `lie_lie_smul_f`, and
`lie_skew` for the reversed-order cases) together with `rel_ef`/`rel_he`/`rel_hf`. -/
private theorem Φ_bracket_basis (t : IsSl2Triple h e f) (i j : Fin 3) :
    (Φ t ⁅subalgebraBasis (K := K) t i, subalgebraBasis (K := K) t j⁆ :
        Module.End K (StandardSl2Module K n))
      = ⁅(Φ t (subalgebraBasis (K := K) t i) : Module.End K (StandardSl2Module K n)),
          (Φ t (subalgebraBasis (K := K) t j) : Module.End K (StandardSl2Module K n))⁆ := by
  fin_cases i <;> fin_cases j
  · -- (e,e)
    rw [lie_subalgebraBasis t _ _ 0 0 (by simp), zero_smul, map_zero, Φ_apply]
    rw [LieRing.of_associative_ring_bracket, sub_self]
  · -- (e,f) ↦ h
    rw [lie_subalgebraBasis t _ _ 2 1 (by simpa using t.lie_e_f), one_smul, Φ_apply, Φ_apply,
      Φ_apply]
    simpa using rel_ef.symm
  · -- (e,h) ↦ -2e
    rw [lie_subalgebraBasis t _ _ 0 (-2)
      (by show ⁅e, h⁆ = (-2 : K) • e; rw [← lie_skew, t.lie_h_e_smul K]; module), map_smul,
      Φ_apply, Φ_apply, Φ_apply]
    show (-2 : K) • ρE = ⁅(ρE : Module.End K (StandardSl2Module K n)), ρH⁆
    rw [endLieSkew, rel_he]
    module
  · -- (f,e) ↦ -h
    rw [lie_subalgebraBasis t _ _ 2 (-1)
      (by show ⁅f, e⁆ = (-1 : K) • h; rw [← lie_skew, t.lie_e_f]; module), map_smul, Φ_apply,
      Φ_apply, Φ_apply]
    show (-1 : K) • ρH = ⁅(ρF : Module.End K (StandardSl2Module K n)), ρE⁆
    rw [endLieSkew, rel_ef]
    module
  · -- (f,f)
    rw [lie_subalgebraBasis t _ _ 1 0 (by simp), zero_smul, map_zero, Φ_apply]
    rw [LieRing.of_associative_ring_bracket, sub_self]
  · -- (f,h) ↦ 2f
    rw [lie_subalgebraBasis t _ _ 1 2
      (by show ⁅f, h⁆ = (2 : K) • f; rw [← lie_skew, t.lie_lie_smul_f K]; module), map_smul,
      Φ_apply, Φ_apply, Φ_apply]
    show (2 : K) • ρF = ⁅(ρF : Module.End K (StandardSl2Module K n)), ρH⁆
    rw [endLieSkew, rel_hf]
    module
  · -- (h,e) ↦ 2e
    rw [lie_subalgebraBasis t _ _ 0 2 (by simpa using t.lie_h_e_smul K), map_smul, Φ_apply,
      Φ_apply, Φ_apply]
    show (2 : K) • ρE = ⁅(ρH : Module.End K (StandardSl2Module K n)), ρE⁆
    rw [rel_he]
  · -- (h,f) ↦ -2f
    rw [lie_subalgebraBasis t _ _ 1 (-2)
      (by show ⁅h, f⁆ = (-2 : K) • f; rw [t.lie_lie_smul_f K]; module), map_smul, Φ_apply,
      Φ_apply, Φ_apply]
    show (-2 : K) • ρF = ⁅(ρH : Module.End K (StandardSl2Module K n)), ρF⁆
    rw [rel_hf]
  · -- (h,h)
    rw [lie_subalgebraBasis t _ _ 2 0 (by simp), zero_smul, map_zero, Φ_apply]
    rw [LieRing.of_associative_ring_bracket, sub_self]

/-- Bracketing on the right by a fixed subalgebra element, as a `K`-linear self-map of the
subalgebra (needed to invoke `Basis.ext` when extending `Φ_bracket_basis` off the basis). -/
private def bracketRight (t : IsSl2Triple h e f) (y : ↥(t.toLieSubalgebra (R := K))) :
    ↥(t.toLieSubalgebra (R := K)) →ₗ[K] ↥(t.toLieSubalgebra (R := K)) where
  toFun x := ⁅x, y⁆
  map_add' a b := add_lie a b y
  map_smul' c a := smul_lie c a y

/-- Bracketing on the left by a fixed subalgebra element. -/
private def bracketLeft (t : IsSl2Triple h e f) (x : ↥(t.toLieSubalgebra (R := K))) :
    ↥(t.toLieSubalgebra (R := K)) →ₗ[K] ↥(t.toLieSubalgebra (R := K)) where
  toFun y := ⁅x, y⁆
  map_add' := lie_add x
  map_smul' c a := lie_smul c x a

/-- Bracketing on the right by a fixed endomorphism, as a `K`-linear self-map. -/
private def endBracketRight (z : Module.End K (StandardSl2Module K n)) :
    Module.End K (StandardSl2Module K n) →ₗ[K] Module.End K (StandardSl2Module K n) where
  toFun w := ⁅w, z⁆
  map_add' a b := endAddLie a b z
  map_smul' c a := endSmulLie c a z

/-- Bracketing on the left by a fixed endomorphism. -/
private def endBracketLeft (z : Module.End K (StandardSl2Module K n)) :
    Module.End K (StandardSl2Module K n) →ₗ[K] Module.End K (StandardSl2Module K n) where
  toFun w := ⁅z, w⁆
  map_add' := endLieAdd z
  map_smul' c a := endLieSmul c z a

/-- **`Φ` respects brackets against an arbitrary left argument, for basis `y`**: extends
`Φ_bracket_basis` off the `i`-basis-vector by `Basis.ext`, since both sides of the desired
equation are `K`-linear in `x` (the left argument) once `y = subalgebraBasis t j` is fixed. -/
private theorem Φ_lie_basis_right (t : IsSl2Triple h e f) (j : Fin 3)
    (x : ↥(t.toLieSubalgebra (R := K))) :
    Φ (K := K) (n := n) t
        ⁅x, subalgebraBasis (K := K) t j⁆
      =
      ⁅(Φ (K := K) (n := n) t x :
          Module.End K (StandardSl2Module K n)),
        (Φ (K := K) (n := n) t
            (subalgebraBasis (K := K) t j) :
          Module.End K (StandardSl2Module K n))⁆ := by
  let bj : ↥(t.toLieSubalgebra (R := K)) :=
    subalgebraBasis (K := K) t j

  let Φn :
      ↥(t.toLieSubalgebra (R := K)) →ₗ[K]
        Module.End K (StandardSl2Module K n) :=
    Φ (K := K) (n := n) t

  have key :
      Φn.comp (bracketRight (K := K) t bj)
        =
      (endBracketRight (K := K) (n := n) (Φn bj)).comp Φn := by
    apply (subalgebraBasis (K := K) t).ext
    intro i
    change
      Φn ⁅subalgebraBasis (K := K) t i, bj⁆
        =
      ⁅(Φn (subalgebraBasis (K := K) t i) :
          Module.End K (StandardSl2Module K n)),
        (Φn bj :
          Module.End K (StandardSl2Module K n))⁆
    dsimp only [bj, Φn]
    exact Φ_bracket_basis (K := K) (n := n) t i j

  have hx := DFunLike.congr_fun key x
  change
    Φn ⁅x, bj⁆
      =
    ⁅Φn x, Φn bj⁆
    at hx
  simpa [Φn, bj] using hx

/-- **`Φ` is a Lie-algebra homomorphism**. -/
private theorem Φ_lie (t : IsSl2Triple h e f)
    (x y : ↥(t.toLieSubalgebra (R := K))) :
    Φ (K := K) (n := n) t ⁅x, y⁆
      =
      ⁅(Φ (K := K) (n := n) t x :
          Module.End K (StandardSl2Module K n)),
        (Φ (K := K) (n := n) t y :
          Module.End K (StandardSl2Module K n))⁆ := by
  let Φn :
      ↥(t.toLieSubalgebra (R := K)) →ₗ[K]
        Module.End K (StandardSl2Module K n) :=
    Φ (K := K) (n := n) t

  have key :
      Φn.comp (bracketLeft (K := K) t x)
        =
      (endBracketLeft (K := K) (Φn x)).comp Φn := by
    apply (subalgebraBasis (K := K) t).ext
    intro j

    change
      Φn ⁅x, subalgebraBasis (K := K) t j⁆
        =
      ⁅(Φn x : Module.End K (StandardSl2Module K n)),
        (Φn (subalgebraBasis (K := K) t j) :
          Module.End K (StandardSl2Module K n))⁆

    dsimp only [Φn]
    exact Φ_lie_basis_right (K := K) (n := n) t j x

  have hy := DFunLike.congr_fun key y
  change
    Φn ⁅x, y⁆
      =
    ⁅Φn x, Φn y⁆
    at hy
  simpa [Φn] using hy

end Construction

/-- **Standard module `V(n)`, module structure** (`def:sl2-standard-module`).
Given an `sl₂`-triple `(h,e,f)` in `L`, `StandardSl2Module K n` carries a
`LieRingModule` structure for the generated subalgebra, with
`h ⬝ v k = (n - 2k) • v k`, `f ⬝ v k = v (k+1)` (and `f ⬝ v n = 0), and
`e ⬝ v k = (k * (n - k + 1)) • v (k-1)` (and `e ⬝ v 0 = 0`). -/
@[reducible] def standardSl2ModuleLieRingModule
    [CharZero K]
    (t : IsSl2Triple h e f) :
    LieRingModule
      (↥(t.toLieSubalgebra (R := K)))
      (StandardSl2Module K n) where

  bracket x v :=
    (Φ (K := K) (n := n) t x :
      Module.End K (StandardSl2Module K n)) v

  add_lie x y v := by
    change
      (Φ (K := K) (n := n) t (x + y) :
          Module.End K (StandardSl2Module K n)) v
        =
      (Φ (K := K) (n := n) t x :
          Module.End K (StandardSl2Module K n)) v
        +
      (Φ (K := K) (n := n) t y :
          Module.End K (StandardSl2Module K n)) v
    rw [map_add]
    rfl

  lie_add x v w := by
    change
      (Φ (K := K) (n := n) t x :
          Module.End K (StandardSl2Module K n)) (v + w)
        =
      (Φ (K := K) (n := n) t x :
          Module.End K (StandardSl2Module K n)) v
        +
      (Φ (K := K) (n := n) t x :
          Module.End K (StandardSl2Module K n)) w
    exact
      map_add
        (Φ (K := K) (n := n) t x :
          Module.End K (StandardSl2Module K n))
        v w

  leibniz_lie x y v := by
    change
      (Φ (K := K) (n := n) t x :
          Module.End K (StandardSl2Module K n))
          ((Φ (K := K) (n := n) t y :
              Module.End K (StandardSl2Module K n)) v)
        =
      (Φ (K := K) (n := n) t ⁅x, y⁆ :
          Module.End K (StandardSl2Module K n)) v
        +
      (Φ (K := K) (n := n) t y :
          Module.End K (StandardSl2Module K n))
          ((Φ (K := K) (n := n) t x :
              Module.End K (StandardSl2Module K n)) v)

    rw [Φ_lie (K := K) (n := n) t x y]
    rw [LieRing.of_associative_ring_bracket]
    simp only [
      LinearMap.sub_apply,
      Module.End.mul_apply
    ]
    abel


/-- **Standard module `V(n)`, module structure, continued**. -/
theorem standardSl2ModuleLieModule
    [CharZero K]
    (t : IsSl2Triple h e f) :
    letI := standardSl2ModuleLieRingModule (K := K) (n := n) t
    LieModule
      K
      (↥(t.toLieSubalgebra (R := K)))
      (StandardSl2Module K n) := by
  letI := standardSl2ModuleLieRingModule (K := K) (n := n) t

  constructor

  · intro c x v
    change
      (Φ (K := K) (n := n) t (c • x) :
          Module.End K (StandardSl2Module K n)) v
        =
      c •
        (Φ (K := K) (n := n) t x :
          Module.End K (StandardSl2Module K n)) v
    rw [map_smul]
    rfl

  · intro c x v
    change
      (Φ (K := K) (n := n) t x :
          Module.End K (StandardSl2Module K n)) (c • v)
        =
      c •
        (Φ (K := K) (n := n) t x :
          Module.End K (StandardSl2Module K n)) v
    exact
      map_smul
        (Φ (K := K) (n := n) t x :
          Module.End K (StandardSl2Module K n))
        c v

/-! ### Public action formulas

`standardSl2ModuleLieRingModule`'s bracket is built from the private `Φ`/`ρE`/`ρF`/`ρH`
machinery above, none of which is visible outside this file. The theorems below expose the
action of `h`, `e`, `f` themselves on the standard basis `v`, matching the formulas already
recorded in `standardSl2ModuleLieRingModule`'s own docstring, for downstream files (e.g.
`Sl2/Classification.lean`) that need to match a module's own action against the standard one. -/

section PublicApi

variable [CharZero K]

omit [CharZero K] in
private theorem h_mem_subalgebra (t : IsSl2Triple h e f) : h ∈ t.toLieSubalgebra (R := K) :=
  IsSl2Triple.mem_toLieSubalgebra_iff.mpr ⟨0, 0, 1, by rw [t.lie_e_f]; module⟩

omit [CharZero K] in
private theorem e_mem_subalgebra (t : IsSl2Triple h e f) : e ∈ t.toLieSubalgebra (R := K) :=
  IsSl2Triple.mem_toLieSubalgebra_iff.mpr ⟨1, 0, 0, by module⟩

omit [CharZero K] in
private theorem f_mem_subalgebra (t : IsSl2Triple h e f) : f ∈ t.toLieSubalgebra (R := K) :=
  IsSl2Triple.mem_toLieSubalgebra_iff.mpr ⟨0, 1, 0, by module⟩

/-- The subalgebra element corresponding to `h`, as used by the theorems below. -/
def hSub (t : IsSl2Triple h e f) : ↥(t.toLieSubalgebra (R := K)) := ⟨h, h_mem_subalgebra t⟩

/-- The subalgebra element corresponding to `e`, as used by the theorems below. -/
def eSub (t : IsSl2Triple h e f) : ↥(t.toLieSubalgebra (R := K)) := ⟨e, e_mem_subalgebra t⟩

/-- The subalgebra element corresponding to `f`, as used by the theorems below. -/
def fSub (t : IsSl2Triple h e f) : ↥(t.toLieSubalgebra (R := K)) := ⟨f, f_mem_subalgebra t⟩

private theorem hSub_eq (t : IsSl2Triple h e f) :
    hSub (K := K) t = subalgebraBasis (K := K) t 2 := by
  apply Subtype.ext; simp [hSub, subalgebraBasis, Basis.mk_apply, efhSub]

private theorem eSub_eq (t : IsSl2Triple h e f) :
    eSub (K := K) t = subalgebraBasis (K := K) t 0 := by
  apply Subtype.ext; simp [eSub, subalgebraBasis, Basis.mk_apply, efhSub]

private theorem fSub_eq (t : IsSl2Triple h e f) :
    fSub (K := K) t = subalgebraBasis (K := K) t 1 := by
  apply Subtype.ext; simp [fSub, subalgebraBasis, Basis.mk_apply, efhSub]

theorem standardSl2ModuleLieRingModule_h_apply (t : IsSl2Triple h e f) (k : Fin (n + 1)) :
    letI := standardSl2ModuleLieRingModule (K := K) (n := n) t
    ⁅hSub (K := K) t, StandardSl2Module.v (K := K) k⁆
      = ((n : K) - 2 * (k : ℕ)) • StandardSl2Module.v k := by
  letI := standardSl2ModuleLieRingModule (K := K) (n := n) t
  show (Φ (K := K) (n := n) t (hSub (K := K) t) :
    Module.End K (StandardSl2Module K n)) (StandardSl2Module.v k) = _
  rw [hSub_eq, Φ_apply]
  exact ρH_v k

theorem standardSl2ModuleLieRingModule_e_apply_zero (t : IsSl2Triple h e f) :
    letI := standardSl2ModuleLieRingModule (K := K) (n := n) t
    ⁅eSub (K := K) t, StandardSl2Module.v (K := K) (⟨0, Nat.succ_pos n⟩ : Fin (n + 1))⁆
      = (0 : StandardSl2Module K n) := by
  letI := standardSl2ModuleLieRingModule (K := K) (n := n) t
  show (Φ (K := K) (n := n) t (eSub (K := K) t) :
    Module.End K (StandardSl2Module K n)) (StandardSl2Module.v ⟨0, Nat.succ_pos n⟩) = _
  rw [eSub_eq, Φ_apply]
  exact ρE_v_zero

theorem standardSl2ModuleLieRingModule_e_apply_pos (t : IsSl2Triple h e f)
    (k : Fin (n + 1)) (hk : 0 < (k : ℕ)) :
    letI := standardSl2ModuleLieRingModule (K := K) (n := n) t
    ⁅eSub (K := K) t, StandardSl2Module.v (K := K) k⁆
      = ((k : ℕ) * (n - (k : ℕ) + 1) : K) • StandardSl2Module.v ⟨(k : ℕ) - 1, by omega⟩ := by
  letI := standardSl2ModuleLieRingModule (K := K) (n := n) t
  show (Φ (K := K) (n := n) t (eSub (K := K) t) :
    Module.End K (StandardSl2Module K n)) (StandardSl2Module.v k) = _
  rw [eSub_eq, Φ_apply]
  exact ρE_v_pos k hk

theorem standardSl2ModuleLieRingModule_f_apply_lt (t : IsSl2Triple h e f)
    (k : Fin (n + 1)) (hk : (k : ℕ) < n) :
    letI := standardSl2ModuleLieRingModule (K := K) (n := n) t
    ⁅fSub (K := K) t, StandardSl2Module.v (K := K) k⁆ = StandardSl2Module.v ⟨(k : ℕ) + 1, by omega⟩ := by
  letI := standardSl2ModuleLieRingModule (K := K) (n := n) t
  show (Φ (K := K) (n := n) t (fSub (K := K) t) :
    Module.End K (StandardSl2Module K n)) (StandardSl2Module.v k) = _
  rw [fSub_eq, Φ_apply]
  exact ρF_v_lt k hk

theorem standardSl2ModuleLieRingModule_f_apply_last (t : IsSl2Triple h e f) :
    letI := standardSl2ModuleLieRingModule (K := K) (n := n) t
    ⁅fSub (K := K) t, StandardSl2Module.v (K := K) (Fin.last n)⁆ = (0 : StandardSl2Module K n) := by
  letI := standardSl2ModuleLieRingModule (K := K) (n := n) t
  show (Φ (K := K) (n := n) t (fSub (K := K) t) :
    Module.End K (StandardSl2Module K n)) (StandardSl2Module.v (Fin.last n)) = _
  rw [fSub_eq, Φ_apply]
  exact ρF_v_last

omit [CharZero K] in
/-- `hSub t`, `eSub t`, `fSub t` themselves form an `IsSl2Triple` **within the subalgebra**
`↥(t.toLieSubalgebra K)` (as opposed to `t` itself, whose `h, e, f` live in the ambient `L`).
Useful for restricting sl2-representation-theory results (e.g.
`IsSl2Triple.exists_hasPrimitiveVectorWith`) to a submodule that is invariant under the
subalgebra generated by `t` but not necessarily under all of `L`. -/
theorem isSl2Triple_sub (t : IsSl2Triple h e f) :
    IsSl2Triple (hSub (K := K) t) (eSub (K := K) t) (fSub (K := K) t) where
  h_ne_zero hc := t.h_ne_zero (by simpa [hSub, Subtype.ext_iff] using hc)
  lie_e_f := by
    apply Subtype.ext
    show (↑(⁅eSub (K := K) t, fSub (K := K) t⁆) : L) = (↑(hSub (K := K) t) : L)
    rw [LieSubalgebra.coe_bracket]
    exact t.lie_e_f
  lie_h_e_nsmul := by
    rw [two_smul]
    apply Subtype.ext
    show (↑(⁅hSub (K := K) t, eSub (K := K) t⁆) : L)
        = (↑(eSub (K := K) t) : L) + (↑(eSub (K := K) t) : L)
    rw [LieSubalgebra.coe_bracket]
    have := t.lie_h_e_nsmul
    rwa [two_smul] at this
  lie_h_f_nsmul := by
    rw [two_smul]
    apply Subtype.ext
    show (↑(⁅hSub (K := K) t, fSub (K := K) t⁆) : L)
        = -((↑(fSub (K := K) t) : L) + (↑(fSub (K := K) t) : L))
    rw [LieSubalgebra.coe_bracket]
    have := t.lie_h_f_nsmul
    rwa [two_smul] at this

end PublicApi

end QuantumRepresentationTheory
