import Mathlib
import QuantumRepresentationTheory.Sl2.Basic

/-!
# Sl2/Classification

Part of the blueprint for algebraic quantum representation theory.
See `blueprint/src/content.tex`, §"Classification of irreducible $\sltwo$-modules"
(`sec:sl2-classification`).
-/

noncomputable section

namespace QuantumRepresentationTheory

variable {K L M : Type*} [Field K] [LieRing L] [LieAlgebra K L]
    [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
    {h e f : L} {m : M} {n : ℕ}

/-- The vectors `m, fm, …, fⁿm` of the primitive-vector string, indexed by `Fin (n+1)`. -/
def stringVecs (f : L) (m : M) (n : ℕ) (k : Fin (n + 1)) : M :=
  (LieModule.toEnd K L M f ^ (k : ℕ)) m

/-- **Linear independence of the primitive-vector string** (`thm:sl2-string-independent`).

The hypothesis `CharZero K` is necessary and was missing from an earlier version
of this statement: Mathlib's own
`IsSl2Triple.HasPrimitiveVectorWith.pow_toEnd_f_ne_zero_of_eq_nat`, which this
proof relies on to keep the string from collapsing to `0` early, itself requires
`CharZero`. Concretely, in characteristic `2` the adjoint representation of
`sl₂` on itself has a primitive vector `m = e` of weight `n = 2` (since `2 = 0`
in `K`), but `f²·e = -2f = 0`, so the length-`3` string `(e, ±h, 0)` is not
linearly independent. -/
theorem string_linearIndependent [CharZero K] {t : IsSl2Triple h e f}
    (P : t.HasPrimitiveVectorWith m (n : K)) :
    LinearIndependent K (stringVecs (K := K) f m n) := by
  have hne : ∀ k : Fin (n + 1), stringVecs (K := K) f m n k ≠ 0 := fun k =>
    P.pow_toEnd_f_ne_zero_of_eq_nat rfl (Nat.lt_succ_iff.mp k.isLt)
  have heig : ∀ k : Fin (n + 1),
      (LieModule.toEnd K L M h).HasEigenvector ((n : K) - 2 * (k : ℕ))
        (stringVecs (K := K) f m n k) := by
    intro k
    refine ⟨?_, hne k⟩
    rw [Module.End.mem_eigenspace_iff, LieModule.toEnd_apply_apply]
    exact P.lie_h_pow_toEnd_f k
  have hinj : Function.Injective (fun k : Fin (n + 1) => (n : K) - 2 * (k : ℕ)) := by
    intro k₁ k₂ hk
    simp only [sub_right_inj, mul_eq_mul_left_iff] at hk
    rcases hk with hk | hk
    · exact Fin.ext (Nat.cast_injective hk)
    · norm_num at hk
  exact (LieModule.toEnd K L M h).eigenvectors_linearIndependent'
    (fun k : Fin (n + 1) => (n : K) - 2 * (k : ℕ)) hinj (stringVecs (K := K) f m n) heig

/-- The span of the primitive-vector string, as a plain `K`-submodule. -/
def stringSpan (f : L) (m : M) (n : ℕ) : Submodule K M :=
  Submodule.span K (Set.range (stringVecs (K := K) f m n))

/-- **The string spans a Lie submodule** (`thm:sl2-string-submodule`): the span of the
string is invariant under `h`, `e`, and `f`, hence underlies a `LieSubmodule`.

The conclusion is a `LieSubmodule` **for the subalgebra generated by `t`**
(`↥(t.toLieSubalgebra K)`, automatically a `LieRingModule` of `M` by restricting the
ambient `L`-action via `LieSubalgebra.lieRingModule`), not for the ambient `L`. This is a
correction of an earlier version of this file, which stated it (and everything after it) for
generic `L`: a `LieSubmodule K L M` demands invariance under *all* of `L`, but the string is
only manifestly invariant under `h,e,f`, and a generic ambient `L` gives no reason for those to
span it (nothing stops `L` from having extra elements unrelated to the triple `t`). Restricting
to the subalgebra is both the provable and the mathematically meaningful statement: it is the
`sl₂`-submodule generated by the triple, and this is how every downstream theorem in this file
already phrases `classification`'s conclusion.

The hypothesis `[FiniteDimensional K M]` is likewise necessary and was missing from an earlier
version: Mathlib's `pow_toEnd_f_eq_zero_of_eq_nat` (used here to see that the string
terminates, `f • stringVecs n = 0`) genuinely needs finite length — infinite-dimensional Verma
modules have primitive vectors of every natural-number weight `n` whose `f`-string never
closes. -/
theorem exists_stringLieSubmodule [CharZero K] [FiniteDimensional K M] {t : IsSl2Triple h e f}
    (P : t.HasPrimitiveVectorWith m (n : K)) :
    ∃ N : LieSubmodule K ↥(t.toLieSubalgebra (R := K)) M, (N : Submodule K M) = stringSpan f m n := by
  -- `ψ k` is the `k`-th vector of the (possibly out-of-range) `f`-string; every `ψ k` lies in
  -- `stringSpan f m n`, either directly (`k ≤ n`) or as `0` (`k > n`, via `f`'s string closing).
  set ψ : ℕ → M := fun k => (LieModule.toEnd K L M f ^ k) m with hψ_def
  have hψ_mem : ∀ k : ℕ, ψ k ∈ stringSpan (K := K) f m n := by
    intro k
    by_cases hk : k ≤ n
    · exact Submodule.subset_span ⟨⟨k, Nat.lt_succ_of_le hk⟩, rfl⟩
    · rw [not_le] at hk
      have h0 : ψ (n + 1) = 0 := P.pow_toEnd_f_eq_zero_of_eq_nat rfl
      have hexpand : ψ k = (LieModule.toEnd K L M f ^ (k - (n + 1))) (ψ (n + 1)) := by
        rw [hψ_def]
        show _ = ((LieModule.toEnd K L M f ^ (k - (n + 1))) *
          (LieModule.toEnd K L M f ^ (n + 1))) m
        rw [← pow_add]
        congr 2
        omega
      rw [hexpand, h0, map_zero]
      exact (stringSpan f m n).zero_mem
  refine ⟨{ __ := stringSpan f m n, lie_mem := ?_ }, rfl⟩
  intro x w hw
  show ⁅x, w⁆ ∈ stringSpan f m n
  have hw' : w ∈ stringSpan f m n := hw
  clear hw
  induction hw' using Submodule.span_induction with
  | zero => simp
  | add u v _ _ hu' hv' => rw [lie_add]; exact (stringSpan f m n).add_mem hu' hv'
  | smul c u _ hu' => rw [lie_smul]; exact (stringSpan f m n).smul_mem c hu'
  | mem u hu =>
    obtain ⟨k, rfl⟩ := hu
    obtain ⟨c₁, c₂, c₃, hc⟩ := IsSl2Triple.mem_toLieSubalgebra_iff.mp x.property
    rw [LieSubalgebra.coe_bracket_of_module, hc, t.lie_e_f]
    simp only [add_lie, smul_lie]
    refine (stringSpan f m n).add_mem
      ((stringSpan f m n).add_mem
        ((stringSpan f m n).smul_mem c₁ ?_) ((stringSpan f m n).smul_mem c₂ ?_))
      ((stringSpan f m n).smul_mem c₃ ?_)
    · -- `⁅e, ψ k⁆`
      rcases eq_or_ne (k : ℕ) 0 with hk0 | hk0
      · have : stringVecs (K := K) f m n k = m := by
          simp only [stringVecs, hk0, pow_zero, Module.End.one_apply]
        rw [this, P.lie_e]
        exact (stringSpan f m n).zero_mem
      · obtain ⟨j, hj⟩ := Nat.exists_eq_succ_of_ne_zero hk0
        have hkj : stringVecs (K := K) f m n k = ψ (j + 1) := by
          simp only [stringVecs, hψ_def, hj]
        rw [hkj, P.lie_e_pow_succ_toEnd_f j]
        exact (stringSpan f m n).smul_mem _ (hψ_mem j)
    · -- `⁅f, ψ k⁆`
      have hfk : ⁅f, stringVecs (K := K) f m n k⁆ = ψ ((k : ℕ) + 1) :=
        P.lie_f_pow_toEnd_f k
      rw [hfk]
      exact hψ_mem _
    · -- `⁅h, ψ k⁆`
      have hhk : ⁅h, stringVecs (K := K) f m n k⁆
          = ((n : K) - 2 * (k : ℕ)) • stringVecs (K := K) f m n k :=
        P.lie_h_pow_toEnd_f k
      rw [hhk]
      exact (stringSpan f m n).smul_mem _ (Submodule.subset_span ⟨k, rfl⟩)

/-- **Irreducibility forces the string to span** (`thm:sl2-irreducible-spans`).

As with `exists_stringLieSubmodule`, irreducibility is stated **for the subalgebra**
`↥(t.toLieSubalgebra K)`, not for the ambient `L` (see that theorem's doc comment for why). -/
theorem stringSpan_eq_top {t : IsSl2Triple h e f}
    [LieModule.IsIrreducible K ↥(t.toLieSubalgebra (R := K)) M]
    (P : t.HasPrimitiveVectorWith m (n : K)) (N : LieSubmodule K ↥(t.toLieSubalgebra (R := K)) M)
    (hN : (N : Submodule K M) = stringSpan f m n) : N = ⊤ := by
  rcases IsSimpleOrder.eq_bot_or_eq_top N with hbot | htop
  · exfalso
    apply P.ne_zero
    have hm_mem : m ∈ (N : Submodule K M) := by
      rw [hN]
      exact Submodule.subset_span ⟨⟨0, Nat.succ_pos n⟩, by simp [stringVecs]⟩
    rw [hbot] at hm_mem
    simpa using hm_mem
  · exact htop

/-- **Basis theorem** (`thm:sl2-basis-theorem`): for `M` irreducible with primitive vector
`m` of weight `n`, the string `m, fm, …, fⁿm` is a basis of `M`.

Irreducibility is stated for the subalgebra, as in `stringSpan_eq_top`. -/
theorem string_isBasis [CharZero K] [FiniteDimensional K M] {t : IsSl2Triple h e f}
    [LieModule.IsIrreducible K ↥(t.toLieSubalgebra (R := K)) M]
    (P : t.HasPrimitiveVectorWith m (n : K)) :
    LinearIndependent K (stringVecs (K := K) f m n) ∧
      Submodule.span K (Set.range (stringVecs (K := K) f m n)) = ⊤ := by
  refine ⟨string_linearIndependent P, ?_⟩
  obtain ⟨N, hN⟩ := exists_stringLieSubmodule P
  have := stringSpan_eq_top P N hN
  rw [this] at hN
  simpa [stringSpan] using hN.symm

/-- **Basis theorem, dimension count** (`thm:sl2-basis-theorem`). -/
theorem finrank_eq_succ [CharZero K] [FiniteDimensional K M] {t : IsSl2Triple h e f}
    [LieModule.IsIrreducible K ↥(t.toLieSubalgebra (R := K)) M]
    (P : t.HasPrimitiveVectorWith m (n : K)) :
    Module.finrank K M = n + 1 := by
  obtain ⟨hli, hspan⟩ := string_isBasis P
  have hbasis : Module.Basis (Fin (n + 1)) K M := Module.Basis.mk hli hspan.ge
  simpa using (Module.finrank_eq_card_basis hbasis)

/-- **Classification of irreducible $\sltwo$-modules** (`thm:sl2-classification`).
Every finite-dimensional irreducible module for an `sl₂`-triple, over an algebraically
closed field of characteristic zero, is isomorphic (as a module for the generated
subalgebra) to the standard module `V(n)` for a unique `n`. -/
theorem classification [IsAlgClosed K] [CharZero K] [FiniteDimensional K M]
    [LieModule.IsIrreducible K L M] (t : IsSl2Triple h e f) :
    ∃ n : ℕ, letI := standardSl2ModuleLieRingModule (K := K) (n := n) t
      Nonempty (M ≃ₗ⁅K, ↥(t.toLieSubalgebra (R := K))⁆ StandardSl2Module K n) := by
  sorry

/-- **Uniqueness of the highest weight** (`thm:sl2-uniqueness-hw`): the `n` produced by
`classification` is determined by `M` alone, namely `n = finrank K M - 1`. -/
theorem classification_n_eq_finrank_sub_one [IsAlgClosed K] [CharZero K] [FiniteDimensional K M]
    [LieModule.IsIrreducible K L M] (t : IsSl2Triple h e f) {n : ℕ}
    (hn : letI := standardSl2ModuleLieRingModule (K := K) (n := n) t
      Nonempty (M ≃ₗ⁅K, ↥(t.toLieSubalgebra (R := K))⁆ StandardSl2Module K n)) :
    n = Module.finrank K M - 1 := by
  sorry

end QuantumRepresentationTheory
