import Mathlib
import QuantumRepresentationTheory.Sl2.Basic
import QuantumRepresentationTheory.Sl2.Classification
import QuantumRepresentationTheory.Representation.Basic

/-!
# Sl2/CommutingActions

Part of the blueprint for algebraic quantum representation theory.
See `blueprint/src/content.tex`, §"Commuting $\sltwo$-actions and tensor products"
(`sec:sl2-commuting`) — the largest hidden node in the roadmap: without this, equal
Casimir eigenvalues for two commuting `sl₂`-triples do not by themselves give a
dimension formula.
-/

noncomputable section

namespace QuantumRepresentationTheory

open scoped TensorProduct

variable {K V : Type*} [Field K] [AddCommGroup V] [Module K V]


/-- **Existence of a joint primitive vector**: given two commuting `sl₂`-triples on a
finite-dimensional space, there is a single nonzero vector `m0` that is simultaneously
primitive for both — `e1 m0 = 0`, `e2 m0 = 0`, `h1 m0 = n1 • m0`, `h2 m0 = n2 • m0` for
some `n1, n2 : ℕ`.

Constructed in two stages: first get a primitive vector `m1` for `t1` on all of `V` (Mathlib's
`exists_hasPrimitiveVectorWith`), then note `W := ker e1 ⊓ ker (h1 - n1•1)` (the `n1`-weight
space of `e1`'s kernel) is invariant under `h2, e2, f2` (since those commute with both `e1` and
`h1`), nonzero (it contains `m1`), and hence — packaged as a `LieSubmodule` for the subalgebra
generated by `t2` via `isSl2Triple_sub` — has its own primitive vector for `t2`, which lies in
`W` and is therefore automatically primitive for `t1` too. -/
private theorem exists_joint_primitive [IsAlgClosed K] [CharZero K] [FiniteDimensional K V]
    {h1 e1 f1 h2 e2 f2 : Module.End K V}
    (t1 : IsSl2Triple h1 e1 f1) (t2 : IsSl2Triple h2 e2 f2)
    (hcomm : ∀ x ∈ ({h1, e1, f1} : Set (Module.End K V)),
      ∀ y ∈ ({h2, e2, f2} : Set (Module.End K V)), ⁅x, y⁆ = 0) :
    ∃ (n1 n2 : ℕ) (m0 : V), m0 ≠ 0 ∧
      t1.HasPrimitiveVectorWith m0 (n1 : K) ∧ t2.HasPrimitiveVectorWith m0 (n2 : K) := by
  have hV : Nontrivial V := by
    rcases subsingleton_or_nontrivial V with hsub | hnt
    · exact absurd (LinearMap.ext fun v => @Subsingleton.elim V hsub _ _ : h1 = 0) t1.h_ne_zero
    · exact hnt
  obtain ⟨μ1, m1, hm1ne, P1⟩ := t1.exists_hasPrimitiveVectorWith (R := K) (M := V)
  obtain ⟨n1, hn1⟩ := P1.exists_nat
  subst hn1
  set W : Submodule K V := LinearMap.ker e1 ⊓ LinearMap.ker (h1 - (n1 : K) • (1 : Module.End K V))
    with hW_def
  have hm1W : m1 ∈ W := by
    rw [hW_def, Submodule.mem_inf, LinearMap.mem_ker, LinearMap.mem_ker]
    refine ⟨by simpa [Module.End.lie_apply] using P1.lie_e, ?_⟩
    have hh := P1.lie_h
    simp only [Module.End.lie_apply] at hh
    simp only [LinearMap.sub_apply, LinearMap.smul_apply, Module.End.one_apply, sub_eq_zero]
    exact hh
  have hWinv : ∀ y : Module.End K V, (⁅e1, y⁆ : Module.End K V) = 0 →
      (⁅h1, y⁆ : Module.End K V) = 0 → ∀ v ∈ W, y v ∈ W := by
    intro y hey hhy v hv
    rw [hW_def, Submodule.mem_inf, LinearMap.mem_ker, LinearMap.mem_ker] at hv ⊢
    obtain ⟨hv1, hv2⟩ := hv
    have hce : e1 * y = y * e1 := by
      rwa [LieRing.of_associative_ring_bracket, sub_eq_zero] at hey
    have hch : h1 * y = y * h1 := by
      rwa [LieRing.of_associative_ring_bracket, sub_eq_zero] at hhy
    refine ⟨?_, ?_⟩
    · have := congrArg (fun T : Module.End K V => T v) hce
      simp only [Module.End.mul_apply] at this
      rw [this, hv1, map_zero]
    · have hv2' : h1 v = (n1 : K) • v := by
        simpa [LinearMap.sub_apply, LinearMap.smul_apply, Module.End.one_apply, sub_eq_zero]
          using hv2
      have heq := congrArg (fun T : Module.End K V => T v) hch
      simp only [Module.End.mul_apply] at heq
      simp only [LinearMap.sub_apply, LinearMap.smul_apply, Module.End.one_apply, sub_eq_zero]
      rw [heq, hv2', map_smul]
  have hWh2 : ∀ v ∈ W, h2 v ∈ W :=
    hWinv h2 (hcomm e1 (by simp) h2 (by simp)) (hcomm h1 (by simp) h2 (by simp))
  have hWe2 : ∀ v ∈ W, e2 v ∈ W :=
    hWinv e2 (hcomm e1 (by simp) e2 (by simp)) (hcomm h1 (by simp) e2 (by simp))
  have hWf2 : ∀ v ∈ W, f2 v ∈ W :=
    hWinv f2 (hcomm e1 (by simp) f2 (by simp)) (hcomm h1 (by simp) f2 (by simp))
  have hlie_mem : ∀ (x : ↥(t2.toLieSubalgebra (R := K))) (v : V), v ∈ W →
      (⁅(x : Module.End K V), v⁆ : V) ∈ W := by
    intro x v hv
    obtain ⟨c1, c2, c3, hc⟩ := IsSl2Triple.mem_toLieSubalgebra_iff.mp x.property
    rw [hc, t2.lie_e_f]
    simp only [add_lie, smul_lie]
    exact W.add_mem (W.add_mem (W.smul_mem c1 (hWe2 v hv)) (W.smul_mem c2 (hWf2 v hv)))
      (W.smul_mem c3 (hWh2 v hv))
  set N : LieSubmodule K ↥(t2.toLieSubalgebra (R := K)) V :=
    { __ := W, lie_mem := fun {x v} hv => hlie_mem x v hv } with hN_def
  have hNW : (N : Submodule K V) = W := rfl
  haveI : Nontrivial ↥N := by
    rw [LieSubmodule.nontrivial_iff_ne_bot]
    intro hbot
    apply hm1ne
    have hm1N : m1 ∈ N := by rw [← hNW] at hm1W; exact hm1W
    rw [hbot] at hm1N
    simpa using hm1N
  haveI : FiniteDimensional K ↥N :=
    FiniteDimensional.finiteDimensional_submodule (N : Submodule K V)
  obtain ⟨ν, w0, hw0ne, P2⟩ :=
    (isSl2Triple_sub (K := K) t2).exists_hasPrimitiveVectorWith (R := K) (M := ↥N)
  obtain ⟨n2, hn2⟩ := P2.exists_nat
  subst hn2
  set m0 : V := (w0 : V) with hm0_def
  have hm0ne : m0 ≠ 0 := fun hz => hw0ne (Subtype.ext (by simpa [hm0_def] using hz))
  have hm0W : m0 ∈ W := by
    rw [hm0_def, ← hNW]
    exact w0.property
  have he1m0 : e1 m0 = 0 := by
    have h := hm0W
    rw [hW_def, Submodule.mem_inf, LinearMap.mem_ker] at h
    exact h.1
  have hh1m0 : h1 m0 = (n1 : K) • m0 := by
    have h := hm0W
    rw [hW_def, Submodule.mem_inf, LinearMap.mem_ker] at h
    simpa [LinearMap.sub_apply, LinearMap.smul_apply, Module.End.one_apply, sub_eq_zero]
      using h.2
  have he2m0 : e2 m0 = 0 := by
    have hh := P2.lie_e
    have hh' : (↑(⁅eSub (K := K) t2, w0⁆) : V) = (↑(0 : ↥N) : V) := by rw [hh]
    rwa [LieSubmodule.coe_bracket, LieSubalgebra.coe_bracket_of_module, Module.End.lie_apply,
      ZeroMemClass.coe_zero] at hh'
  have hh2m0 : h2 m0 = (n2 : K) • m0 := by
    have hh := P2.lie_h
    have hh' : (↑(⁅hSub (K := K) t2, w0⁆) : V) = (↑((n2 : K) • w0) : V) := by rw [hh]
    rwa [LieSubmodule.coe_bracket, LieSubalgebra.coe_bracket_of_module, Module.End.lie_apply,
      LieSubmodule.coe_smul] at hh'
  exact ⟨n1, n2, m0, hm0ne, ⟨hm0ne, hh1m0, he1m0⟩, ⟨hm0ne, hh2m0, he2m0⟩⟩

/-- The ambient tautological action of `Module.End K V` on `V` reproduces `LieModule.toEnd`,
since `⁅x, v⁆ = x v` for the associative-ring bracket. Used to bridge `stringVecs`'s
`LieModule.toEnd`-based formulas with plain operator powers, where commutation facts
(`hcomm`) live. -/
private theorem toEnd_ambient_eq (x : Module.End K V) :
    LieModule.toEnd K (Module.End K V) V x = x := by
  ext v
  rw [LieModule.toEnd_apply_apply, Module.End.lie_apply]

/-- **Dimension count via the bivariate string basis.** Given a joint primitive vector `m0`
(weight `n1` for `t1`, `n2` for `t2`), the vectors `f1^a (f2^b m0)` for `a ≤ n1, b ≤ n2` form a
basis of `V`: linearly independent (via a combined eigenvalue for `h1 + (n1+1)•h2`, chosen so
that `(n1-2a) + (n1+1)(n2-2b)` is injective in `(a,b)`), and their span is invariant under all
six generators (so `hirr` forces it to be everything). -/
private theorem exists_bivariate_basis [IsAlgClosed K] [CharZero K] [FiniteDimensional K V]
    {h1 e1 f1 h2 e2 f2 : Module.End K V}
    (t1 : IsSl2Triple h1 e1 f1) (t2 : IsSl2Triple h2 e2 f2)
    (hcomm : ∀ x ∈ ({h1, e1, f1} : Set (Module.End K V)),
      ∀ y ∈ ({h2, e2, f2} : Set (Module.End K V)), ⁅x, y⁆ = 0)
    (hirr : ∀ W : Submodule K V,
      (∀ x ∈ ({h1, e1, f1, h2, e2, f2} : Set (Module.End K V)), ∀ v ∈ W, x v ∈ W) →
      W = ⊥ ∨ W = ⊤) :
    ∃ n1 n2 : ℕ, Module.finrank K V = (n1 + 1) * (n2 + 1) := by
  obtain ⟨n1, n2, m0, hm0ne, P1, P2⟩ := exists_joint_primitive t1 t2 hcomm
  set mb : Fin (n2 + 1) → V := stringVecs (K := K) f2 m0 n2 with hmb_def
  have hmb0 : mb 0 = m0 := by simp [hmb_def, stringVecs]
  have hmb_ne : ∀ b : Fin (n2 + 1), mb b ≠ 0 := fun b =>
    P2.pow_toEnd_f_ne_zero_of_eq_nat rfl (Nat.lt_succ_iff.mp b.isLt)
  have hmb_eq_pow : ∀ b : Fin (n2 + 1), mb b = (f2 ^ (b : ℕ)) m0 := by
    intro b
    show (LieModule.toEnd K (Module.End K V) V f2 ^ (b : ℕ)) m0 = _
    rw [toEnd_ambient_eq]
  have hcommute_e1_f2 : Commute e1 f2 := by
    rw [commute_iff_eq]
    have h0 := hcomm e1 (by simp) f2 (by simp)
    rwa [LieRing.of_associative_ring_bracket, sub_eq_zero] at h0
  have hcommute_h1_f2 : Commute h1 f2 := by
    rw [commute_iff_eq]
    have h0 := hcomm h1 (by simp) f2 (by simp)
    rwa [LieRing.of_associative_ring_bracket, sub_eq_zero] at h0
  have hh1m0 : h1 m0 = (n1 : K) • m0 := by
    have := P1.lie_h; simpa [Module.End.lie_apply] using this
  have he1m0 : e1 m0 = 0 := by
    have := P1.lie_e; simpa [Module.End.lie_apply] using this
  have hmb_primitive1 : ∀ b : Fin (n2 + 1), t1.HasPrimitiveVectorWith (mb b) (n1 : K) := by
    intro b
    refine ⟨hmb_ne b, ?_, ?_⟩
    · show (⁅h1, mb b⁆ : V) = (n1 : K) • mb b
      rw [Module.End.lie_apply, hmb_eq_pow]
      have hc : h1 * f2 ^ (b : ℕ) = f2 ^ (b : ℕ) * h1 := (hcommute_h1_f2.pow_right (b : ℕ)).eq
      have := congrArg (fun T : Module.End K V => T m0) hc
      simp only [Module.End.mul_apply] at this
      rw [this, hh1m0, map_smul, ← hmb_eq_pow]
    · show (⁅e1, mb b⁆ : V) = 0
      rw [Module.End.lie_apply, hmb_eq_pow]
      have hc : e1 * f2 ^ (b : ℕ) = f2 ^ (b : ℕ) * e1 := (hcommute_e1_f2.pow_right (b : ℕ)).eq
      have := congrArg (fun T : Module.End K V => T m0) hc
      simp only [Module.End.mul_apply] at this
      rw [this, he1m0, map_zero]
  -- `sv2 a b := f1^a (mb b)`, the bivariate primitive-vector string.
  set sv2 : Fin (n1 + 1) → Fin (n2 + 1) → V := fun a b => stringVecs (K := K) f1 (mb b) n1 a
    with hsv2_def
  have hsv2_ne : ∀ a b, sv2 a b ≠ 0 := fun a b =>
    (hmb_primitive1 b).pow_toEnd_f_ne_zero_of_eq_nat rfl (Nat.lt_succ_iff.mp a.isLt)
  have hsv2_h1 : ∀ a b, (⁅h1, sv2 a b⁆ : V) = ((n1 : K) - 2 * (a : ℕ)) • sv2 a b := fun a b =>
    (hmb_primitive1 b).lie_h_pow_toEnd_f a
  -- Commutation of `h2, e2, f2` with `f1`'s powers, bridging `stringVecs`'s `toEnd`-power form.
  have hcommute_f1 : ∀ y ∈ ({h2, e2, f2} : Set (Module.End K V)), Commute f1 y := by
    intro y hy
    rw [commute_iff_eq]
    have h0 := hcomm f1 (by simp) y hy
    rwa [LieRing.of_associative_ring_bracket, sub_eq_zero] at h0
  have hpush : ∀ (y : Module.End K V), Commute f1 y → ∀ a b, y (sv2 a b) =
      stringVecs (K := K) f1 (y (mb b)) n1 a := by
    intro y hy a b
    show y ((LieModule.toEnd K (Module.End K V) V f1 ^ (a : ℕ)) (mb b)) = _
    rw [toEnd_ambient_eq]
    have hc : (f1 ^ (a : ℕ)) * y = y * (f1 ^ (a : ℕ)) := (hy.pow_left (a : ℕ)).eq
    have heq := congrArg (fun T : Module.End K V => T (mb b)) hc
    simp only [Module.End.mul_apply] at heq
    rw [← heq]
    show (LieModule.toEnd K (Module.End K V) V f1 ^ (a : ℕ)) (y (mb b)) = _
    rfl
  have hh2mb : ∀ b : Fin (n2 + 1), h2 (mb b) = ((n2 : K) - 2 * (b : ℕ)) • mb b := by
    intro b
    have hh := P2.lie_h_pow_toEnd_f (b : ℕ)
    simpa [Module.End.lie_apply, hmb_def, stringVecs] using hh
  have hsv2_h2 : ∀ a b, h2 (sv2 a b) = ((n2 : K) - 2 * (b : ℕ)) • sv2 a b := by
    intro a b
    rw [hpush h2 (hcommute_f1 h2 (by simp)) a b, hh2mb b]
    show (LieModule.toEnd K (Module.End K V) V f1 ^ (a : ℕ)) (((n2 : K) - 2 * (b : ℕ)) • mb b) = _
    rw [map_smul]
    rfl
  -- **Linear independence** of the bivariate string, via the combined operator
  -- `h1 + (n1+1)•h2`: its eigenvalue on `sv2 a b` is `(n1-2a) + (n1+1)(n2-2b)`, injective in
  -- `(a,b)` since `n1+1` exceeds the possible spread `n1` of the first coordinate.
  have hweight_inj : Function.Injective (fun p : Fin (n1 + 1) × Fin (n2 + 1) =>
      ((n1 : K) - 2 * (p.1 : ℕ)) + ((n1 : K) + 1) * ((n2 : K) - 2 * (p.2 : ℕ))) := by
    rintro ⟨a, b⟩ ⟨a', b'⟩ heq
    simp only at heq
    have hZ : ((n1 : ℤ) - 2 * (a : ℕ) + ((n1 : ℤ) + 1) * ((n2 : ℤ) - 2 * (b : ℕ)))
        = ((n1 : ℤ) - 2 * (a' : ℕ) + ((n1 : ℤ) + 1) * ((n2 : ℤ) - 2 * (b' : ℕ))) := by
      exact_mod_cast heq
    have ha : (a : ℕ) ≤ n1 := Nat.lt_succ_iff.mp a.isLt
    have ha' : (a' : ℕ) ≤ n1 := Nat.lt_succ_iff.mp a'.isLt
    have hZ2 : 2 * ((a' : ℤ) - a) = 2 * (((n1 : ℤ) + 1) * ((b : ℤ) - b')) := by linear_combination hZ
    have hZ' : (a' : ℤ) - a = ((n1 : ℤ) + 1) * ((b : ℤ) - b') := by linarith
    have hbeq : (b : ℤ) = (b' : ℤ) := by
      by_contra hne
      have hb1 : (1 : ℤ) ≤ |(b : ℤ) - b'| := Int.one_le_abs (by omega)
      have hbound : (n1 : ℤ) + 1 ≤ |((n1 : ℤ) + 1) * ((b : ℤ) - b')| := by
        rw [abs_mul, abs_of_nonneg (by positivity : (0:ℤ) ≤ (n1:ℤ)+1)]
        nlinarith
      rw [← hZ'] at hbound
      have habound : |(a' : ℤ) - a| ≤ (n1 : ℤ) := by
        rw [abs_le]; omega
      omega
    have haeq : (a : ℤ) = (a' : ℤ) := by
      rw [hbeq] at hZ'
      simp only [sub_self, mul_zero] at hZ'
      omega
    exact Prod.ext (Fin.ext (by exact_mod_cast haeq)) (Fin.ext (by exact_mod_cast hbeq))
  have hsv2_eigen : ∀ p : Fin (n1 + 1) × Fin (n2 + 1),
      (h1 + ((n1 : K) + 1) • h2).HasEigenvector
        (((n1 : K) - 2 * (p.1 : ℕ)) + ((n1 : K) + 1) * ((n2 : K) - 2 * (p.2 : ℕ)))
        (sv2 p.1 p.2) := by
    intro ⟨a, b⟩
    refine ⟨?_, hsv2_ne a b⟩
    rw [Module.End.mem_eigenspace_iff]
    have hh1 : h1 (sv2 a b) = ((n1 : K) - 2 * (a : ℕ)) • sv2 a b := by
      have := hsv2_h1 a b; rwa [Module.End.lie_apply] at this
    show h1 (sv2 a b) + ((n1 : K) + 1) • h2 (sv2 a b) = _
    rw [hh1, hsv2_h2 a b, smul_smul, ← add_smul]
  have hsv2_li : LinearIndependent K (fun p : Fin (n1 + 1) × Fin (n2 + 1) => sv2 p.1 p.2) :=
    (h1 + ((n1 : K) + 1) • h2).eigenvectors_linearIndependent' _ hweight_inj _ hsv2_eigen
  -- **Spanning**: the span of the bivariate string is invariant under all six generators
  -- (via `hspanMem`, which also absorbs the "string closes" boundary cases), hence `hirr`
  -- forces it to be everything.
  set Sspan : Submodule K V :=
      Submodule.span K (Set.range (fun p : Fin (n1 + 1) × Fin (n2 + 1) => sv2 p.1 p.2))
    with hSspan_def
  have hspanMem : ∀ a b : ℕ, (LieModule.toEnd K (Module.End K V) V f1 ^ a)
      ((LieModule.toEnd K (Module.End K V) V f2 ^ b) m0) ∈ Sspan := by
    intro a b
    by_cases hb : b ≤ n2
    · by_cases ha : a ≤ n1
      · have heqv : (LieModule.toEnd K (Module.End K V) V f1 ^ a)
            ((LieModule.toEnd K (Module.End K V) V f2 ^ b) m0)
            = sv2 ⟨a, Nat.lt_succ_of_le ha⟩ ⟨b, Nat.lt_succ_of_le hb⟩ := rfl
        rw [heqv]
        exact Submodule.subset_span ⟨(⟨a, Nat.lt_succ_of_le ha⟩, ⟨b, Nat.lt_succ_of_le hb⟩), rfl⟩
      · push Not at ha
        have h0 : (LieModule.toEnd K (Module.End K V) V f1 ^ (n1 + 1))
            ((LieModule.toEnd K (Module.End K V) V f2 ^ b) m0) = 0 :=
          (hmb_primitive1 ⟨b, Nat.lt_succ_of_le hb⟩).pow_toEnd_f_eq_zero_of_eq_nat rfl
        have hpoweq : (LieModule.toEnd K (Module.End K V) V f1) ^ a
            = (LieModule.toEnd K (Module.End K V) V f1) ^ (a - (n1 + 1))
              * (LieModule.toEnd K (Module.End K V) V f1) ^ (n1 + 1) := by
          rw [← pow_add]; congr 1; omega
        have hsplit : (LieModule.toEnd K (Module.End K V) V f1 ^ a)
            ((LieModule.toEnd K (Module.End K V) V f2 ^ b) m0)
            = (LieModule.toEnd K (Module.End K V) V f1 ^ (a - (n1 + 1)))
              ((LieModule.toEnd K (Module.End K V) V f1 ^ (n1 + 1))
                ((LieModule.toEnd K (Module.End K V) V f2 ^ b) m0)) := by
          rw [hpoweq, Module.End.mul_apply]
        rw [hsplit, h0, map_zero]
        exact Sspan.zero_mem
    · push Not at hb
      have h0 : (LieModule.toEnd K (Module.End K V) V f2 ^ (n2 + 1)) m0 = 0 :=
        P2.pow_toEnd_f_eq_zero_of_eq_nat rfl
      have hpoweq : (LieModule.toEnd K (Module.End K V) V f2) ^ b
          = (LieModule.toEnd K (Module.End K V) V f2) ^ (b - (n2 + 1))
            * (LieModule.toEnd K (Module.End K V) V f2) ^ (n2 + 1) := by
        rw [← pow_add]; congr 1; omega
      have hsplit : (LieModule.toEnd K (Module.End K V) V f2 ^ b) m0
          = (LieModule.toEnd K (Module.End K V) V f2 ^ (b - (n2 + 1)))
              ((LieModule.toEnd K (Module.End K V) V f2 ^ (n2 + 1)) m0) := by
        rw [hpoweq, Module.End.mul_apply]
      rw [hsplit, h0, map_zero, map_zero]
      exact Sspan.zero_mem
  have hSpan_h1 : ∀ v ∈ Sspan, h1 v ∈ Sspan := by
    intro v hv
    induction hv using Submodule.span_induction with
    | zero => simp
    | add u w _ _ hu hw => rw [map_add]; exact Sspan.add_mem hu hw
    | smul c u _ hu => rw [map_smul]; exact Sspan.smul_mem c hu
    | mem u hu =>
      obtain ⟨⟨a, b⟩, rfl⟩ := hu
      have hh1 := hsv2_h1 a b
      rw [Module.End.lie_apply] at hh1
      rw [hh1]
      exact Sspan.smul_mem _ (Submodule.subset_span ⟨(a, b), rfl⟩)
  have hSpan_h2 : ∀ v ∈ Sspan, h2 v ∈ Sspan := by
    intro v hv
    induction hv using Submodule.span_induction with
    | zero => simp
    | add u w _ _ hu hw => rw [map_add]; exact Sspan.add_mem hu hw
    | smul c u _ hu => rw [map_smul]; exact Sspan.smul_mem c hu
    | mem u hu =>
      obtain ⟨⟨a, b⟩, rfl⟩ := hu
      rw [hsv2_h2 a b]
      exact Sspan.smul_mem _ (Submodule.subset_span ⟨(a, b), rfl⟩)
  have hSpan_f1 : ∀ v ∈ Sspan, f1 v ∈ Sspan := by
    intro v hv
    induction hv using Submodule.span_induction with
    | zero => simp
    | add u w _ _ hu hw => rw [map_add]; exact Sspan.add_mem hu hw
    | smul c u _ hu => rw [map_smul]; exact Sspan.smul_mem c hu
    | mem u hu =>
      obtain ⟨⟨a, b⟩, rfl⟩ := hu
      have hfk := (hmb_primitive1 b).lie_f_pow_toEnd_f (a : ℕ)
      rw [Module.End.lie_apply] at hfk
      show f1 ((LieModule.toEnd K (Module.End K V) V f1 ^ (a : ℕ)) (mb b)) ∈ Sspan
      rw [hfk]
      exact hspanMem ((a : ℕ) + 1) (b : ℕ)
  have hSpan_f2 : ∀ v ∈ Sspan, f2 v ∈ Sspan := by
    intro v hv
    induction hv using Submodule.span_induction with
    | zero => simp
    | add u w _ _ hu hw => rw [map_add]; exact Sspan.add_mem hu hw
    | smul c u _ hu => rw [map_smul]; exact Sspan.smul_mem c hu
    | mem u hu =>
      obtain ⟨⟨a, b⟩, rfl⟩ := hu
      rw [hpush f2 (hcommute_f1 f2 (by simp)) a b]
      have hfmb := P2.lie_f_pow_toEnd_f (b : ℕ)
      rw [Module.End.lie_apply] at hfmb
      show stringVecs (K := K) f1
          (f2 ((LieModule.toEnd K (Module.End K V) V f2 ^ (b : ℕ)) m0)) n1 a ∈ Sspan
      rw [hfmb]
      exact hspanMem (a : ℕ) ((b : ℕ) + 1)
  have hSpan_e1 : ∀ v ∈ Sspan, e1 v ∈ Sspan := by
    intro v hv
    induction hv using Submodule.span_induction with
    | zero => simp
    | add u w _ _ hu hw => rw [map_add]; exact Sspan.add_mem hu hw
    | smul c u _ hu => rw [map_smul]; exact Sspan.smul_mem c hu
    | mem u hu =>
      obtain ⟨⟨a, b⟩, rfl⟩ := hu
      show e1 ((LieModule.toEnd K (Module.End K V) V f1 ^ (a : ℕ)) (mb b)) ∈ Sspan
      rcases Nat.eq_zero_or_pos (a : ℕ) with ha0 | hapos
      · have he := (hmb_primitive1 b).lie_e
        rw [Module.End.lie_apply] at he
        rw [ha0, pow_zero, Module.End.one_apply, he]
        exact Sspan.zero_mem
      · obtain ⟨j, hj⟩ := Nat.exists_eq_succ_of_ne_zero hapos.ne'
        have he := (hmb_primitive1 b).lie_e_pow_succ_toEnd_f j
        rw [Module.End.lie_apply] at he
        rw [hj, he]
        exact Sspan.smul_mem _ (hspanMem j (b : ℕ))
  have hSpan_e2 : ∀ v ∈ Sspan, e2 v ∈ Sspan := by
    intro v hv
    induction hv using Submodule.span_induction with
    | zero => simp
    | add u w _ _ hu hw => rw [map_add]; exact Sspan.add_mem hu hw
    | smul c u _ hu => rw [map_smul]; exact Sspan.smul_mem c hu
    | mem u hu =>
      obtain ⟨⟨a, b⟩, rfl⟩ := hu
      rw [hpush e2 (hcommute_f1 e2 (by simp)) a b]
      show stringVecs (K := K) f1 (e2 (mb b)) n1 a ∈ Sspan
      rcases Nat.eq_zero_or_pos (b : ℕ) with hb0 | hbpos
      · have hb0' : b = (0 : Fin (n2 + 1)) := Fin.ext hb0
        rw [hb0', hmb0]
        have he := P2.lie_e
        rw [Module.End.lie_apply] at he
        rw [he]
        show (LieModule.toEnd K (Module.End K V) V f1 ^ (a : ℕ)) (0 : V) ∈ Sspan
        rw [map_zero]
        exact Sspan.zero_mem
      · obtain ⟨j, hj⟩ := Nat.exists_eq_succ_of_ne_zero hbpos.ne'
        have he := P2.lie_e_pow_succ_toEnd_f j
        rw [Module.End.lie_apply] at he
        have hmbeq : mb b = (LieModule.toEnd K (Module.End K V) V f2 ^ (b : ℕ)) m0 := rfl
        rw [hmbeq, hj, he]
        show (LieModule.toEnd K (Module.End K V) V f1 ^ (a : ℕ))
            (_ • (LieModule.toEnd K (Module.End K V) V f2 ^ j) m0) ∈ Sspan
        rw [map_smul]
        exact Sspan.smul_mem _ (hspanMem (a : ℕ) j)
  have hSpanTop : Sspan = ⊤ := by
    rcases hirr Sspan (by
      intro x hx v hv
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
      rcases hx with rfl | rfl | rfl | rfl | rfl | rfl
      · exact hSpan_h1 v hv
      · exact hSpan_e1 v hv
      · exact hSpan_f1 v hv
      · exact hSpan_h2 v hv
      · exact hSpan_e2 v hv
      · exact hSpan_f2 v hv) with hbot | htop
    · exfalso
      have hmem : sv2 0 0 ∈ Sspan := Submodule.subset_span ⟨(0, 0), rfl⟩
      rw [hbot] at hmem
      exact hsv2_ne 0 0 (Submodule.mem_bot K |>.mp hmem)
    · exact htop
  set B : Module.Basis (Fin (n1 + 1) × Fin (n2 + 1)) K V := Module.Basis.mk hsv2_li hSpanTop.ge
    with hB_def
  refine ⟨n1, n2, ?_⟩
  rw [Module.finrank_eq_card_basis B, Fintype.card_prod, Fintype.card_fin, Fintype.card_fin]

/-- **Classification of jointly irreducible commuting $\sltwo$-actions**
(`thm:sl2-commuting-classification`). Two `sl₂`-triples of operators on a
finite-dimensional space `V`, commuting with each other and with no proper
subspace invariant under both, force `V` to be linearly isomorphic to a tensor
product `V(m) ⊗ V(n)` of standard modules.

TODO: the isomorphism produced here is only asserted at the level of the
underlying `K`-vector spaces; the stronger statement (that it intertwines
`h1,e1,f1,h2,e2,f2` with the actions on the two tensor factors from
`standardSl2ModuleLieRingModule`) is future work, tracked alongside
`def:rep-bridge`. -/
theorem commuting_classification [IsAlgClosed K] [CharZero K] [FiniteDimensional K V]
    {h1 e1 f1 h2 e2 f2 : Module.End K V}
    (t1 : IsSl2Triple h1 e1 f1) (t2 : IsSl2Triple h2 e2 f2)
    (hcomm : ∀ x ∈ ({h1, e1, f1} : Set (Module.End K V)),
      ∀ y ∈ ({h2, e2, f2} : Set (Module.End K V)), ⁅x, y⁆ = 0)
    (hirr : ∀ W : Submodule K V,
      (∀ x ∈ ({h1, e1, f1, h2, e2, f2} : Set (Module.End K V)), ∀ v ∈ W, x v ∈ W) →
      W = ⊥ ∨ W = ⊤) :
    ∃ m n : ℕ, Nonempty (V ≃ₗ[K] StandardSl2Module K m ⊗[K] StandardSl2Module K n) := by
  obtain ⟨n1, n2, hdim⟩ := exists_bivariate_basis t1 t2 hcomm hirr
  refine ⟨n1, n2, ?_⟩
  have hd : ∀ k : ℕ, Module.finrank K (StandardSl2Module K k) = k + 1 := fun k => by
    show Module.finrank K (Fin (k + 1) → K) = k + 1
    rw [Module.finrank_pi, Fintype.card_fin]
  apply FiniteDimensional.nonempty_linearEquiv_of_finrank_eq
  rw [hdim, Module.finrank_tensorProduct, hd, hd]

/-- **Dimension consequence** of `commuting_classification`: `finrank K V = (m+1)(n+1)`. -/
theorem commuting_classification_finrank [IsAlgClosed K] [CharZero K] [FiniteDimensional K V]
    {h1 e1 f1 h2 e2 f2 : Module.End K V}
    (t1 : IsSl2Triple h1 e1 f1) (t2 : IsSl2Triple h2 e2 f2)
    (hcomm : ∀ x ∈ ({h1, e1, f1} : Set (Module.End K V)),
      ∀ y ∈ ({h2, e2, f2} : Set (Module.End K V)), ⁅x, y⁆ = 0)
    (hirr : ∀ W : Submodule K V,
      (∀ x ∈ ({h1, e1, f1, h2, e2, f2} : Set (Module.End K V)), ∀ v ∈ W, x v ∈ W) →
      W = ⊥ ∨ W = ⊤) :
    ∃ m n : ℕ, Module.finrank K V = (m + 1) * (n + 1) :=
  exists_bivariate_basis t1 t2 hcomm hirr

end QuantumRepresentationTheory
