name = "QuantumRepresentationTheory"
version = "0.1.0"
defaultTargets = ["QuantumRepresentationTheory"]

[[require]]
name = "Physlib"
git = "https://github.com/leanprover-community/physlib.git"
rev = "v4.32.0"


[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"
[[lean_lib]]
name = "QuantumRepresentationTheory"
moreLeanArgs = ["-Dwarn.sorry=false"]