import Mathlib
import QuantumRepresentationTheory.AngularMomentum.Basic
import QuantumRepresentationTheory.Sl2.Basic

/-!
# AngularMomentum/Classification

Part of the blueprint for algebraic quantum representation theory.
See `blueprint/src/content.tex`, §"Spin classification" (`sec:am-classification`).
-/

noncomputable section

namespace QuantumRepresentationTheory

variable {V : Type*} [AddCommGroup V] [Module ℂ V]


namespace AngularMomentumRepresentation

/-- Irreducibility of an angular momentum representation: no proper subspace is
invariant under `Jx`, `Jy`, and `Jz` simultaneously. -/
def IsIrreducible (ρ : AngularMomentumRepresentation V) : Prop :=
  ∀ W : Submodule ℂ V,
    (∀ v ∈ W, ρ.Jx v ∈ W) → (∀ v ∈ W, ρ.Jy v ∈ W) → (∀ v ∈ W, ρ.Jz v ∈ W) →
    W = ⊥ ∨ W = ⊤

/-- **Irreducibility transfers along the bridge** (`thm:am-irreducibility-transfer`):
`ρ.IsIrreducible` agrees with irreducibility of the induced module for the `sl₂`-subalgebra
generated by `(2Jz, J+, J-)` (via the automatic `LieSubalgebra.lieRingModule`/`lieModule`
instances restricting the tautological `Module.End ℂ V`-action on `V`). -/
theorem isIrreducible_iff (ρ : AngularMomentumRepresentation V) :
    ρ.IsIrreducible ↔ LieModule.IsIrreducible ℂ (↥(ρ.isSl2Triple.toLieSubalgebra ℂ)) V := by
  sorry

/-- **Spin classification** (`thm:am-spin-classification`): every finite-dimensional
irreducible angular momentum representation is isomorphic (as a module for the `sl₂`-subalgebra
generated by `(2Jz,J+,J-)`) to the standard module `V(n)`, for a unique `n : ℕ`; the physical
spin is `j = n/2`, of multiplicity (dimension) `n + 1 = 2j + 1`. -/
theorem spin_classification [FiniteDimensional ℂ V] (ρ : AngularMomentumRepresentation V)
    (hirr : ρ.IsIrreducible) :
    ∃ n : ℕ, letI := standardSl2ModuleLieRingModule (K := ℂ) (n := n) ρ.isSl2Triple
      Nonempty (V ≃ₗ⁅ℂ, ↥(ρ.isSl2Triple.toLieSubalgebra ℂ)⁆ StandardSl2Module ℂ n) := by
  sorry

/-- **`J² = Jx²+Jy²+Jz²` is (a rescaling of) the Casimir element** (`thm:am-j2-casimir`):
on an irreducible summand of spin `j = n/2`, `J²` acts as the scalar `j(j+1)`. -/
theorem Jsq_eq_smul [FiniteDimensional ℂ V] (ρ : AngularMomentumRepresentation V)
    (hirr : ρ.IsIrreducible) :
    ∃ n : ℕ, ρ.Jx * ρ.Jx + ρ.Jy * ρ.Jy + ρ.Jz * ρ.Jz =
      ((n : ℂ) / 2 * ((n : ℂ) / 2 + 1)) • (1 : Module.End ℂ V) := by
  sorry

/-- **Magnetic-weight basis** (`def:am-magnetic-basis`): given a primitive vector `v₀` of
weight `n` for the triple `(2Jz, J+, J-)`, the vectors `(J-)ᵏ v₀` for `k = 0,…,n` form a
basis of the irreducible summand, reindexed by the magnetic quantum number `m = n/2 - k`. -/
def magneticBasisVec (ρ : AngularMomentumRepresentation V) {n : ℕ} {v₀ : V}
    (_ : ρ.isSl2Triple.HasPrimitiveVectorWith v₀ (n : ℂ)) (k : Fin (n + 1)) : V :=
  (ρ.Jm ^ (k : ℕ)) v₀

end AngularMomentumRepresentation

end QuantumRepresentationTheory
