import Mathlib
import QuantumRepresentationTheory.AngularMomentum.Basic
import QuantumRepresentationTheory.Sl2.Basic

/-!
# AngularMomentum/Classification

Part of the blueprint for algebraic quantum representation theory.
See `blueprint/src/content.tex`, §"Spin classification" (`sec:am-classification`).
-/

noncomputable section

namespace QuantumRepresentationTheory

variable {V : Type*} [AddCommGroup V] [Module ℂ V]


namespace AngularMomentumRepresentation

/-- Irreducibility of an angular momentum representation: no proper subspace is
invariant under `Jx`, `Jy`, and `Jz` simultaneously. -/
def IsIrreducible (ρ : AngularMomentumRepresentation V) : Prop :=
  ∀ W : Submodule ℂ V,
    (∀ v ∈ W, ρ.Jx v ∈ W) → (∀ v ∈ W, ρ.Jy v ∈ W) → (∀ v ∈ W, ρ.Jz v ∈ W) →
    W = ⊥ ∨ W = ⊤

/-- **Irreducibility transfers along the bridge** (`thm:am-irreducibility-transfer`):
`ρ.IsIrreducible` agrees with irreducibility of the induced module for the `sl₂`-subalgebra
generated by `(2Jz, J+, J-)` (via the automatic `LieSubalgebra.lieRingModule`/`lieModule`
instances restricting the tautological `Module.End ℂ V`-action on `V`). -/
theorem isIrreducible_iff (ρ : AngularMomentumRepresentation V) (hz : ρ.Jz ≠ 0) :
    ρ.IsIrreducible ↔ LieModule.IsIrreducible ℂ (↥((ρ.isSl2Triple hz).toLieSubalgebra ℂ)) V := by
  set t := ρ.isSl2Triple hz with ht_def
  set L' := t.toLieSubalgebra ℂ with hL'_def
  have hV : Nontrivial V := by
    rcases subsingleton_or_nontrivial V with hsub | hnt
    · exact absurd (LinearMap.ext fun v => @Subsingleton.elim V hsub _ _ : ρ.Jz = 0) hz
    · exact hnt
  have hcomm : (⁅ρ.Jp, ρ.Jm⁆ : Module.End ℂ V) = (2 : ℂ) • ρ.Jz := comm_p_m ρ
  have hJx_mem : ρ.Jx ∈ L' :=
    IsSl2Triple.mem_toLieSubalgebra_iff.mpr
      ⟨(1 / 2 : ℂ), (1 / 2 : ℂ), 0, by simp [Jp, Jm]; module⟩
  have hJy_mem : ρ.Jy ∈ L' :=
    IsSl2Triple.mem_toLieSubalgebra_iff.mpr
      ⟨(-Complex.I / 2 : ℂ), (Complex.I / 2 : ℂ), 0, by
        simp only [Jp, Jm, zero_smul, add_zero]
        rw [smul_add, smul_sub, smul_smul, smul_smul]
        have : (-Complex.I / 2 * Complex.I : ℂ) = 1 / 2 := by
          rw [div_mul_eq_mul_div, neg_mul, Complex.I_mul_I]; ring
        have hI : (Complex.I / 2 * Complex.I : ℂ) = -(1 / 2) := by
          rw [div_mul_eq_mul_div, Complex.I_mul_I]; ring
        rw [this, hI]
        module⟩
  have hJz_mem : ρ.Jz ∈ L' :=
    IsSl2Triple.mem_toLieSubalgebra_iff.mpr
      ⟨0, 0, (1 / 2 : ℂ), by rw [hcomm]; module⟩
  constructor
  · intro hirr
    refine LieModule.IsIrreducible.mk (fun N hN => ?_)
    have hINVx : ∀ v ∈ (N : Submodule ℂ V), ρ.Jx v ∈ (N : Submodule ℂ V) := fun v hv => by
      have := N.lie_mem (x := (⟨ρ.Jx, hJx_mem⟩ : L')) hv
      simpa [LieSubalgebra.coe_bracket_of_module, Module.End.lie_apply] using this
    have hINVy : ∀ v ∈ (N : Submodule ℂ V), ρ.Jy v ∈ (N : Submodule ℂ V) := fun v hv => by
      have := N.lie_mem (x := (⟨ρ.Jy, hJy_mem⟩ : L')) hv
      simpa [LieSubalgebra.coe_bracket_of_module, Module.End.lie_apply] using this
    have hINVz : ∀ v ∈ (N : Submodule ℂ V), ρ.Jz v ∈ (N : Submodule ℂ V) := fun v hv => by
      have := N.lie_mem (x := (⟨ρ.Jz, hJz_mem⟩ : L')) hv
      simpa [LieSubalgebra.coe_bracket_of_module, Module.End.lie_apply] using this
    rcases hirr (N : Submodule ℂ V) hINVx hINVy hINVz with hbot | htop
    · exact absurd ((LieSubmodule.toSubmodule_eq_bot N).mp hbot) hN
    · exact (LieSubmodule.toSubmodule_eq_top N).mp htop
  · intro hirr W hWx hWy hWz
    have hlie : ∀ {x : L'} {v : V}, v ∈ W → (⁅x, v⁆ : V) ∈ W := by
      intro x v hv
      obtain ⟨c1, c2, c3, hc⟩ := IsSl2Triple.mem_toLieSubalgebra_iff.mp x.property
      have hJp : ρ.Jp v ∈ W := by
        have : ρ.Jp v = ρ.Jx v + Complex.I • ρ.Jy v := by simp [Jp]
        rw [this]; exact W.add_mem (hWx v hv) (W.smul_mem _ (hWy v hv))
      have hJm : ρ.Jm v ∈ W := by
        have : ρ.Jm v = ρ.Jx v - Complex.I • ρ.Jy v := by simp [Jm]
        rw [this]; exact W.sub_mem (hWx v hv) (W.smul_mem _ (hWy v hv))
      have hcomm_v : (⁅ρ.Jp, ρ.Jm⁆ : Module.End ℂ V) v ∈ W := by
        rw [hcomm]; exact W.smul_mem _ (hWz v hv)
      show (x : Module.End ℂ V) v ∈ W
      rw [hc]
      simp only [LinearMap.add_apply, LinearMap.smul_apply]
      exact W.add_mem (W.add_mem (W.smul_mem _ hJp) (W.smul_mem _ hJm)) (W.smul_mem _ hcomm_v)
    set N : LieSubmodule ℂ L' V := { __ := W, lie_mem := hlie } with hN_def
    have hNW : (N : Submodule ℂ V) = W := rfl
    rcases eq_bot_or_eq_top N with hbot | htop
    · exact Or.inl (hNW ▸ congrArg LieSubmodule.toSubmodule hbot ▸ LieSubmodule.bot_toSubmodule)
    · exact Or.inr (hNW ▸ congrArg LieSubmodule.toSubmodule htop ▸ LieSubmodule.top_toSubmodule)

/-- **Spin classification** (`thm:am-spin-classification`): every finite-dimensional
irreducible angular momentum representation is isomorphic (as a module for the `sl₂`-subalgebra
generated by `(2Jz,J+,J-)`) to the standard module `V(n)`, for a unique `n : ℕ`; the physical
spin is `j = n/2`, of multiplicity (dimension) `n + 1 = 2j + 1`. -/
theorem spin_classification [FiniteDimensional ℂ V] (ρ : AngularMomentumRepresentation V)
    (hz : ρ.Jz ≠ 0) (hirr : ρ.IsIrreducible) :
    ∃ n : ℕ, letI := standardSl2ModuleLieRingModule (K := ℂ) (n := n) (ρ.isSl2Triple hz)
      Nonempty (V ≃ₗ⁅ℂ, ↥((ρ.isSl2Triple hz).toLieSubalgebra ℂ)⁆ StandardSl2Module ℂ n) := by
  sorry

/-- **`J+J- = Jx²+Jy²+Jz`**: the standard ladder-operator identity, a purely algebraic
consequence of the commutation relations (no representation theory needed). Used to
reduce `Jsq_eq_smul` to a statement about `Jp * Jm`, via
`J² = Jp*Jm + Jz*Jz - Jz` (equivalently `Jm*Jp + Jz*Jz + Jz`). -/
private theorem Jp_mul_Jm (ρ : AngularMomentumRepresentation V) :
    ρ.Jp * ρ.Jm = ρ.Jx * ρ.Jx + ρ.Jy * ρ.Jy + ρ.Jz := by
  have hexpand : ρ.Jp * ρ.Jm = ρ.Jx * ρ.Jx + ρ.Jy * ρ.Jy -
      Complex.I • (ρ.Jx * ρ.Jy - ρ.Jy * ρ.Jx) := by
    simp only [Jp, Jm, add_mul, mul_sub, smul_mul_assoc, mul_smul_comm, smul_add, smul_smul,
      Complex.I_mul_I, neg_one_smul, smul_sub]
    abel
  have hcomm : ρ.Jx * ρ.Jy - ρ.Jy * ρ.Jx = Complex.I • ρ.Jz := by
    have := ρ.comm_xy
    rwa [LieRing.of_associative_ring_bracket] at this
  rw [hexpand, hcomm, smul_smul, Complex.I_mul_I, neg_one_smul]
  abel

/-- **`J² = J+J- + Jz² - Jz`**: a purely algebraic consequence of the commutation
relations (no representation theory needed), used to reduce `Jsq_eq_smul` to a
statement about the ladder operators. -/
private theorem Jsq_eq_Jp_mul_Jm (ρ : AngularMomentumRepresentation V) :
    ρ.Jx * ρ.Jx + ρ.Jy * ρ.Jy + ρ.Jz * ρ.Jz =
      ρ.Jp * ρ.Jm + ρ.Jz * ρ.Jz - ρ.Jz := by
  rw [Jp_mul_Jm]; abel

/-- **`J² = Jx²+Jy²+Jz²` is (a rescaling of) the Casimir element** (`thm:am-j2-casimir`):
on an irreducible summand of spin `j = n/2`, `J²` acts as the scalar `j(j+1)`. -/
theorem Jsq_eq_smul [FiniteDimensional ℂ V] (ρ : AngularMomentumRepresentation V)
    (hirr : ρ.IsIrreducible) :
    ∃ n : ℕ, ρ.Jx * ρ.Jx + ρ.Jy * ρ.Jy + ρ.Jz * ρ.Jz =
      ((n : ℂ) / 2 * ((n : ℂ) / 2 + 1)) • (1 : Module.End ℂ V) := by
  sorry

/-- **Magnetic-weight basis** (`def:am-magnetic-basis`): given a primitive vector `v₀` of
weight `n` for the triple `(2Jz, J+, J-)`, the vectors `(J-)ᵏ v₀` for `k = 0,…,n` form a
basis of the irreducible summand, reindexed by the magnetic quantum number `m = n/2 - k`. -/
def magneticBasisVec (ρ : AngularMomentumRepresentation V) (hz : ρ.Jz ≠ 0) {n : ℕ} {v₀ : V}
    (_ : (ρ.isSl2Triple hz).HasPrimitiveVectorWith v₀ (n : ℂ)) (k : Fin (n + 1)) : V :=
  (ρ.Jm ^ (k : ℕ)) v₀

end AngularMomentumRepresentation

end QuantumRepresentationTheory
